In [1]:

!pip install torchgeometry


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.7/42.7 kB 2.9 MB/s eta 0:00:00


In [2]:
!pip show torch


Name: torch
Version: 2.0.0
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /opt/conda/lib/python3.10/site-packages
Requires: filelock, jinja2, networkx, sympy, typing-extensions
Required-by: accelerate, catalyst, easyocr, fastai, kornia, pytorch-ignite, pytorch-lightning, stable-baselines3, timm, torchaudio, torchdata, torchgeometry, torchmetrics, torchtext, torchvision


In [3]:

from torchgeometry.losses import one_hot
import os
import os.path as osp
import pandas as pd
import numpy as np
from PIL import Image
import cv2
import time
import imageio
import matplotlib.pyplot as plt
import time
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.optim import lr_scheduler
from torch import Tensor
from torch.utils.data import Dataset, DataLoader, random_split
from torchvision.transforms import Resize, PILToTensor, ToPILImage, Compose, InterpolationMode
from collections import OrderedDict
import wandb
import albumentations as A
from albumentations.pytorch.transforms import ToTensorV2
import glob
import multiprocessing.pool as mpp
import multiprocessing as mp
import argparse
import torch
import albumentations as albu
from torchvision.transforms import (Pad, ColorJitter, Resize, FiveCrop, RandomResizedCrop,
                                    RandomHorizontalFlip, RandomRotation, RandomVerticalFlip)
import random
import math
import numbers
from PIL import Image, ImageOps, ImageEnhance
import numpy as np
import random
from scipy.ndimage.morphology import generate_binary_structure, binary_erosion
from scipy.ndimage import maximum_filter
from tqdm import tqdm
import pytorch_lightning as pl
from pytorch_lightning.callbacks import ModelCheckpoint
import os
import torch
from torch import nn
import cv2
import numpy as np
import argparse
from pathlib import Path

from pytorch_lightning.loggers import CSVLogger
import random

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [4]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

# Parameters

In [5]:

num_classes = 6

# Number of epoch
epochs = 10

# Hyperparameters for training 
learning_rate = 8e-04
batch_size = 8
display_step = 2

# Model path
checkpoint_path = '/kaggle/working/unet_model.pth'
pretrained_path = "/kaggle/input/unet-checkpoint/unet_model.pth"
# Initialize lists to keep track of loss and accuracy
loss_epoch_array = []
train_accuracy = []
test_accuracy = []
valid_accuracy = []

In [6]:
SEED = 42


def seed_everything(seed):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = True


ImSurf = np.array([255, 255, 255])  # label 0
Building = np.array([255, 0, 0]) # label 1
LowVeg = np.array([255, 255, 0]) # label 2
Tree = np.array([0, 255, 0]) # label 3
Car = np.array([0, 255, 255]) # label 4
Clutter = np.array([0, 0, 255]) # label 5
Boundary = np.array([0, 0, 0]) # label 6
num_classes = 6





def pv2rgb(mask):
    h, w = mask.shape[0], mask.shape[1]
    mask_rgb = np.zeros(shape=(h, w, 3), dtype=np.uint8)
    mask_convert = mask[np.newaxis, :, :]
    mask_rgb[np.all(mask_convert == 3, axis=0)] = [0, 255, 0]
    mask_rgb[np.all(mask_convert == 0, axis=0)] = [255, 255, 255]
    mask_rgb[np.all(mask_convert == 1, axis=0)] = [255, 0, 0]
    mask_rgb[np.all(mask_convert == 2, axis=0)] = [255, 255, 0]
    mask_rgb[np.all(mask_convert == 4, axis=0)] = [0, 204, 255]
    mask_rgb[np.all(mask_convert == 5, axis=0)] = [0, 0, 255]
    return mask_rgb
def label2rgb(mask):
    h, w = mask.shape[0], mask.shape[1]
    mask_rgb = np.zeros(shape=(h, w, 3), dtype=np.uint8)
    mask_convert = mask[np.newaxis, :, :]
    mask_rgb[np.all(mask_convert == 3, axis=0)] = [0, 255, 0]
    mask_rgb[np.all(mask_convert == 0, axis=0)] = [255, 255, 255]
    mask_rgb[np.all(mask_convert == 1, axis=0)] = [255, 0, 0]
    mask_rgb[np.all(mask_convert == 2, axis=0)] = [255, 255, 0]
    mask_rgb[np.all(mask_convert == 4, axis=0)] = [0, 204, 255]
    mask_rgb[np.all(mask_convert == 5, axis=0)] = [0, 0, 255]
    return mask_rgb



def car_color_replace(mask):
    mask = cv2.cvtColor(np.array(mask.copy()), cv2.COLOR_RGB2BGR)
    mask[np.all(mask == [0, 255, 255], axis=-1)] = [0, 204, 255]

    return mask


def rgb_to_2D_label(_label):
    _label = _label.transpose(2, 0, 1)
    label_seg = np.zeros(_label.shape[1:], dtype=np.uint8)
    label_seg[np.all(_label.transpose([1, 2, 0]) == ImSurf, axis=-1)] = 0
    label_seg[np.all(_label.transpose([1, 2, 0]) == Building, axis=-1)] = 1
    label_seg[np.all(_label.transpose([1, 2, 0]) == LowVeg, axis=-1)] = 2
    label_seg[np.all(_label.transpose([1, 2, 0]) == Tree, axis=-1)] = 3
    label_seg[np.all(_label.transpose([1, 2, 0]) == Car, axis=-1)] = 4
    label_seg[np.all(_label.transpose([1, 2, 0]) == Clutter, axis=-1)] = 5
    label_seg[np.all(_label.transpose([1, 2, 0]) == Boundary, axis=-1)] = 6
    return label_seg



    

 # Split Data

 # Dataloader

In [7]:
CLASSES = ('ImSurf', 'Building', 'LowVeg', 'Tree', 'Car', 'Clutter')
PALETTE = [[255, 255, 255], [0, 0, 255], [0, 255, 255], [0, 255, 0], [255, 204, 0], [255, 0, 0]]

ORIGIN_IMG_SIZE = (256, 256)
INPUT_IMG_SIZE = (256, 256)
TEST_IMG_SIZE = (256, 256)

def get_training_transform():
    train_transform = [
        # albu.RandomBrightnessContrast(brightness_limit=0.25, contrast_limit=0.25, p=0.15),
        # albu.RandomRotate90(p=0.25),
        albu.Normalize()
    ]
    return albu.Compose(train_transform)

def get_val_transform():
    val_transform = [
        albu.Normalize()
    ]
    return albu.Compose(val_transform)


def val_aug(img, mask):
    img, mask = np.array(img), np.array(mask)
    aug = get_val_transform()(image=img.copy(), mask=mask.copy())
    img, mask = aug['image'], aug['mask']
    return img, mask


class PotsdamDataset(Dataset):
    def __init__(self, data_root='/kaggle/input/Deep_data_segmentation/Split/Potsdam/', mode='val', img_dir='Image', mask_dir='Label/',
                 img_suffix='.tif', mask_suffix='.png', transform=val_aug, mosaic_ratio=0.0,
                 img_size=ORIGIN_IMG_SIZE):
        self.data_root = data_root
        self.img_dir = img_dir
        self.mask_dir = mask_dir
        self.img_suffix = img_suffix
        self.mask_suffix = mask_suffix
        self.transform = transform
        self.mode = mode
        self.mosaic_ratio = mosaic_ratio
        self.img_size = img_size
        self.img_ids = self.get_img_ids(self.data_root, self.img_dir, self.mask_dir)

    def __getitem__(self, index):
        p_ratio = random.random()
        if p_ratio > self.mosaic_ratio or self.mode == 'val' or self.mode == 'test':
            img, mask = self.load_img_and_mask(index)
            if self.transform:
                img, mask = self.transform(img, mask)
        else:
            img, mask = self.load_mosaic_img_and_mask(index)
            if self.transform:
                img, mask = self.transform(img, mask)

        img = torch.from_numpy(img).permute(2, 0, 1).float()
        mask = torch.from_numpy(mask).long()
        img_id = self.img_ids[index]
        results = dict(img_id=img_id, img=img, gt_semantic_seg=mask)
        return results

    def __len__(self):
        return len(self.img_ids)

    def get_img_ids(self, data_root, img_dir, mask_dir):
        img_filename_list = os.listdir(osp.join(data_root, img_dir))
        mask_filename_list = os.listdir(osp.join(data_root, mask_dir))
        assert len(img_filename_list) == len(mask_filename_list)
        img_ids = [str(id.split('.')[0]) for id in mask_filename_list]
        return img_ids

    def load_img_and_mask(self, index):
        img_id = self.img_ids[index]
        img_name = osp.join(self.data_root, self.img_dir, img_id + self.img_suffix)
        mask_name = osp.join(self.data_root, self.mask_dir, img_id + self.mask_suffix)
        img = Image.open(img_name).convert('RGB')
        mask = Image.open(mask_name).convert('L')
        return img, mask

    def load_mosaic_img_and_mask(self, index):
        indexes = [index] + [random.randint(0, len(self.img_ids) - 1) for _ in range(3)]
        img_a, mask_a = self.load_img_and_mask(indexes[0])
        img_b, mask_b = self.load_img_and_mask(indexes[1])
        img_c, mask_c = self.load_img_and_mask(indexes[2])
        img_d, mask_d = self.load_img_and_mask(indexes[3])

        img_a, mask_a = np.array(img_a), np.array(mask_a)
        img_b, mask_b = np.array(img_b), np.array(mask_b)
        img_c, mask_c = np.array(img_c), np.array(mask_c)
        img_d, mask_d = np.array(img_d), np.array(mask_d)

        w = self.img_size[1]
        h = self.img_size[0]

        start_x = w // 4
        strat_y = h // 4
        # The coordinates of the splice center
        offset_x = random.randint(start_x, (w - start_x))
        offset_y = random.randint(strat_y, (h - strat_y))

        crop_size_a = (offset_x, offset_y)
        crop_size_b = (w - offset_x, offset_y)
        crop_size_c = (offset_x, h - offset_y)
        crop_size_d = (w - offset_x, h - offset_y)

        random_crop_a = albu.RandomCrop(width=crop_size_a[0], height=crop_size_a[1])
        random_crop_b = albu.RandomCrop(width=crop_size_b[0], height=crop_size_b[1])
        random_crop_c = albu.RandomCrop(width=crop_size_c[0], height=crop_size_c[1])
        random_crop_d = albu.RandomCrop(width=crop_size_d[0], height=crop_size_d[1])

        croped_a = random_crop_a(image=img_a.copy(), mask=mask_a.copy())
        croped_b = random_crop_b(image=img_b.copy(), mask=mask_b.copy())
        croped_c = random_crop_c(image=img_c.copy(), mask=mask_c.copy())
        croped_d = random_crop_d(image=img_d.copy(), mask=mask_d.copy())

        img_crop_a, mask_crop_a = croped_a['image'], croped_a['mask']
        img_crop_b, mask_crop_b = croped_b['image'], croped_b['mask']
        img_crop_c, mask_crop_c = croped_c['image'], croped_c['mask']
        img_crop_d, mask_crop_d = croped_d['image'], croped_d['mask']

        top = np.concatenate((img_crop_a, img_crop_b), axis=1)
        bottom = np.concatenate((img_crop_c, img_crop_d), axis=1)
        img = np.concatenate((top, bottom), axis=0)

        top_mask = np.concatenate((mask_crop_a, mask_crop_b), axis=1)
        bottom_mask = np.concatenate((mask_crop_c, mask_crop_d), axis=1)
        mask = np.concatenate((top_mask, bottom_mask), axis=0)
        mask = np.ascontiguousarray(mask)
        img = np.ascontiguousarray(img)

        img = Image.fromarray(img)
        mask = Image.fromarray(mask)

        return img, mask

In [8]:
data_root ="/kaggle/input/Deep_data_segmentation/Split/Potsdam/Image/top_potsdam_4_12_0_25.tif"


if os.path.exists(data_root):
    print(f"The path '{data_root}' exists.")
else:
    print(f"The path '{data_root}' does not exist.")

The path '/kaggle/input/Deep_data_segmentation/Split/Potsdam/Image/top_potsdam_4_12_0_25.tif' exists.


In [9]:

train_dataset = PotsdamDataset(data_root='/kaggle/input/Deep_data_segmentation/Split/Potsdam/', mode='train',
                               mosaic_ratio=0.25, transform=val_aug)

val_dataset = PotsdamDataset(transform=val_aug)
test_dataset = PotsdamDataset(data_root='/kaggle/input/Deep_data_segmentation/Split/Potsdam/Test',
                              transform=val_aug)

train_loader = DataLoader(dataset=train_dataset,
                          batch_size=batch_size,
                          num_workers=0,
                          pin_memory=False,
                          shuffle=True,
                          drop_last=True)

val_loader = DataLoader(dataset=val_dataset,
                        batch_size=batch_size,
                        num_workers=2,
                        shuffle=False,
                        pin_memory=True,
                        drop_last=False)


# Metric

In [10]:
class Evaluator(object):
    def __init__(self, num_class):
        self.num_class = num_class
        self.confusion_matrix = np.zeros((self.num_class,) * 2)
        self.eps = 1e-8

    def get_tp_fp_tn_fn(self):
        tp = np.diag(self.confusion_matrix)
        fp = self.confusion_matrix.sum(axis=0) - np.diag(self.confusion_matrix)
        fn = self.confusion_matrix.sum(axis=1) - np.diag(self.confusion_matrix)
        tn = np.diag(self.confusion_matrix).sum() - np.diag(self.confusion_matrix)
        return tp, fp, tn, fn

    def Precision(self):
        tp, fp, tn, fn = self.get_tp_fp_tn_fn()
        precision = tp / (tp + fp)
        return precision

    def Recall(self):
        tp, fp, tn, fn = self.get_tp_fp_tn_fn()
        recall = tp / (tp + fn)
        return recall

    def F1(self):
        tp, fp, tn, fn = self.get_tp_fp_tn_fn()
        Precision = tp / (tp + fp)
        Recall = tp / (tp + fn)
        F1 = (2.0 * Precision * Recall) / (Precision + Recall)
        return F1

    def OA(self):
        OA = np.diag(self.confusion_matrix).sum() / (self.confusion_matrix.sum() + self.eps)
        return OA

    def Intersection_over_Union(self):
        tp, fp, tn, fn = self.get_tp_fp_tn_fn()
        IoU = tp / (tp + fn + fp)
        return IoU

    def Dice(self):
        tp, fp, tn, fn = self.get_tp_fp_tn_fn()
        Dice = 2 * tp / ((tp + fp) + (tp + fn))
        return Dice

    def Pixel_Accuracy_Class(self):
        #         TP                                  TP+FP
        Acc = np.diag(self.confusion_matrix) / (self.confusion_matrix.sum(axis=0) + self.eps)
        return Acc

    def Frequency_Weighted_Intersection_over_Union(self):
        freq = np.sum(self.confusion_matrix, axis=1) / (np.sum(self.confusion_matrix) + self.eps)
        iou = self.Intersection_over_Union()
        FWIoU = (freq[freq > 0] * iou[freq > 0]).sum()
        return FWIoU

    def _generate_matrix(self, gt_image, pre_image):
        mask = (gt_image >= 0) & (gt_image < self.num_class)
        label = self.num_class * gt_image[mask].astype('int') + pre_image[mask]
        count = np.bincount(label, minlength=self.num_class ** 2)
        confusion_matrix = count.reshape(self.num_class, self.num_class)
        return confusion_matrix

    def add_batch(self, gt_image, pre_image):
        assert gt_image.shape == pre_image.shape, 'pre_image shape {}, gt_image shape {}'.format(pre_image.shape,
                                                                                                 gt_image.shape)
        self.confusion_matrix += self._generate_matrix(gt_image, pre_image)

    def reset(self):
        self.confusion_matrix = np.zeros((self.num_class,) * 2)

In [11]:
!pip install einops

  Obtaining dependency information for einops from https://files.pythonhosted.org/packages/29/0b/2d1c0ebfd092e25935b86509a9a817159212d82aa43d7fb07eca4eeff2c2/einops-0.7.0-py3-none-any.whl.metadata
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.6/44.6 kB 2.6 MB/s eta 0:00:00


# Model

**Encoder Block**

In [12]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from einops import rearrange, repeat

from timm.models.layers import DropPath, to_2tuple, trunc_normal_
import timm


class ConvBNReLU(nn.Sequential):
    def __init__(self, in_channels, out_channels, kernel_size=3, dilation=1, stride=1, norm_layer=nn.BatchNorm2d, bias=False):
        super(ConvBNReLU, self).__init__(
            nn.Conv2d(in_channels, out_channels, kernel_size=kernel_size, bias=bias,
                      dilation=dilation, stride=stride, padding=((stride - 1) + dilation * (kernel_size - 1)) // 2),
            norm_layer(out_channels),
            nn.ReLU6()
        )


class ConvBN(nn.Sequential):
    def __init__(self, in_channels, out_channels, kernel_size=3, dilation=1, stride=1, norm_layer=nn.BatchNorm2d, bias=False):
        super(ConvBN, self).__init__(
            nn.Conv2d(in_channels, out_channels, kernel_size=kernel_size, bias=bias,
                      dilation=dilation, stride=stride, padding=((stride - 1) + dilation * (kernel_size - 1)) // 2),
            norm_layer(out_channels)
        )


class Conv(nn.Sequential):
    def __init__(self, in_channels, out_channels, kernel_size=3, dilation=1, stride=1, bias=False):
        super(Conv, self).__init__(
            nn.Conv2d(in_channels, out_channels, kernel_size=kernel_size, bias=bias,
                      dilation=dilation, stride=stride, padding=((stride - 1) + dilation * (kernel_size - 1)) // 2)
        )


class SeparableConvBNReLU(nn.Sequential):
    def __init__(self, in_channels, out_channels, kernel_size=3, stride=1, dilation=1,
                 norm_layer=nn.BatchNorm2d):
        super(SeparableConvBNReLU, self).__init__(
            nn.Conv2d(in_channels, in_channels, kernel_size, stride=stride, dilation=dilation,
                      padding=((stride - 1) + dilation * (kernel_size - 1)) // 2,
                      groups=in_channels, bias=False),
            norm_layer(out_channels),
            nn.Conv2d(in_channels, out_channels, kernel_size=1, bias=False),
            nn.ReLU6()
        )


class SeparableConvBN(nn.Sequential):
    def __init__(self, in_channels, out_channels, kernel_size=3, stride=1, dilation=1,
                 norm_layer=nn.BatchNorm2d):
        super(SeparableConvBN, self).__init__(
            nn.Conv2d(in_channels, in_channels, kernel_size, stride=stride, dilation=dilation,
                      padding=((stride - 1) + dilation * (kernel_size - 1)) // 2,
                      groups=in_channels, bias=False),
            norm_layer(out_channels),
            nn.Conv2d(in_channels, out_channels, kernel_size=1, bias=False)
        )


class SeparableConv(nn.Sequential):
    def __init__(self, in_channels, out_channels, kernel_size=3, stride=1, dilation=1):
        super(SeparableConv, self).__init__(
            nn.Conv2d(in_channels, in_channels, kernel_size, stride=stride, dilation=dilation,
                      padding=((stride - 1) + dilation * (kernel_size - 1)) // 2,
                      groups=in_channels, bias=False),
            nn.Conv2d(in_channels, out_channels, kernel_size=1, bias=False)
        )


class Mlp(nn.Module):
    def __init__(self, in_features, hidden_features=None, out_features=None, act_layer=nn.ReLU6, drop=0.):
        super().__init__()
        out_features = out_features or in_features
        hidden_features = hidden_features or in_features
        self.fc1 = nn.Conv2d(in_features, hidden_features, 1, 1, 0, bias=True)
        self.act = act_layer()
        self.fc2 = nn.Conv2d(hidden_features, out_features, 1, 1, 0, bias=True)
        self.drop = nn.Dropout(drop, inplace=True)

    def forward(self, x):
        x = self.fc1(x)
        x = self.act(x)
        x = self.drop(x)
        x = self.fc2(x)
        x = self.drop(x)
        return x


class GlobalLocalAttention(nn.Module):
    def __init__(self,
                 dim=256,
                 num_heads=16,
                 qkv_bias=False,
                 window_size=8,
                 relative_pos_embedding=True
                 ):
        super().__init__()
        self.num_heads = num_heads
        head_dim = dim // self.num_heads
        self.scale = head_dim ** -0.5
        self.ws = window_size

        self.qkv = Conv(dim, 3*dim, kernel_size=1, bias=qkv_bias)
        self.local1 = ConvBN(dim, dim, kernel_size=3)
        self.local2 = ConvBN(dim, dim, kernel_size=1)
        self.proj = SeparableConvBN(dim, dim, kernel_size=window_size)

        self.attn_x = nn.AvgPool2d(kernel_size=(window_size, 1), stride=1,  padding=(window_size//2 - 1, 0))
        self.attn_y = nn.AvgPool2d(kernel_size=(1, window_size), stride=1, padding=(0, window_size//2 - 1))

        self.relative_pos_embedding = relative_pos_embedding

        if self.relative_pos_embedding:
            # define a parameter table of relative position bias
            self.relative_position_bias_table = nn.Parameter(
                torch.zeros((2 * window_size - 1) * (2 * window_size - 1), num_heads))  # 2*Wh-1 * 2*Ww-1, nH

            # get pair-wise relative position index for each token inside the window
            coords_h = torch.arange(self.ws)
            coords_w = torch.arange(self.ws)
            coords = torch.stack(torch.meshgrid([coords_h, coords_w]))  # 2, Wh, Ww
            coords_flatten = torch.flatten(coords, 1)  # 2, Wh*Ww
            relative_coords = coords_flatten[:, :, None] - coords_flatten[:, None, :]  # 2, Wh*Ww, Wh*Ww
            relative_coords = relative_coords.permute(1, 2, 0).contiguous()  # Wh*Ww, Wh*Ww, 2
            relative_coords[:, :, 0] += self.ws - 1  # shift to start from 0
            relative_coords[:, :, 1] += self.ws - 1
            relative_coords[:, :, 0] *= 2 * self.ws - 1
            relative_position_index = relative_coords.sum(-1)  # Wh*Ww, Wh*Ww
            self.register_buffer("relative_position_index", relative_position_index)

            trunc_normal_(self.relative_position_bias_table, std=.02)

    def pad(self, x, ps):
        _, _, H, W = x.size()
        if W % ps != 0:
            x = F.pad(x, (0, ps - W % ps), mode='reflect')
        if H % ps != 0:
            x = F.pad(x, (0, 0, 0, ps - H % ps), mode='reflect')
        return x

    def pad_out(self, x):
        x = F.pad(x, pad=(0, 1, 0, 1), mode='reflect')
        return x

    def forward(self, x):
        B, C, H, W = x.shape

        local = self.local2(x) + self.local1(x)

        x = self.pad(x, self.ws)
        B, C, Hp, Wp = x.shape
        qkv = self.qkv(x)

        q, k, v = rearrange(qkv, 'b (qkv h d) (hh ws1) (ww ws2) -> qkv (b hh ww) h (ws1 ws2) d', h=self.num_heads,
                            d=C//self.num_heads, hh=Hp//self.ws, ww=Wp//self.ws, qkv=3, ws1=self.ws, ws2=self.ws)

        dots = (q @ k.transpose(-2, -1)) * self.scale

        if self.relative_pos_embedding:
            relative_position_bias = self.relative_position_bias_table[self.relative_position_index.view(-1)].view(
                self.ws * self.ws, self.ws * self.ws, -1)  # Wh*Ww,Wh*Ww,nH
            relative_position_bias = relative_position_bias.permute(2, 0, 1).contiguous()  # nH, Wh*Ww, Wh*Ww
            dots += relative_position_bias.unsqueeze(0)

        attn = dots.softmax(dim=-1)
        attn = attn @ v

        attn = rearrange(attn, '(b hh ww) h (ws1 ws2) d -> b (h d) (hh ws1) (ww ws2)', h=self.num_heads,
                         d=C//self.num_heads, hh=Hp//self.ws, ww=Wp//self.ws, ws1=self.ws, ws2=self.ws)

        attn = attn[:, :, :H, :W]

        out = self.attn_x(F.pad(attn, pad=(0, 0, 0, 1), mode='reflect')) + \
              self.attn_y(F.pad(attn, pad=(0, 1, 0, 0), mode='reflect'))

        out = out + local
        out = self.pad_out(out)
        out = self.proj(out)
        # print(out.size())
        out = out[:, :, :H, :W]

        return out


class Block(nn.Module):
    def __init__(self, dim=256, num_heads=16,  mlp_ratio=4., qkv_bias=False, drop=0., attn_drop=0.,
                 drop_path=0., act_layer=nn.ReLU6, norm_layer=nn.BatchNorm2d, window_size=8):
        super().__init__()
        self.norm1 = norm_layer(dim)
        self.attn = GlobalLocalAttention(dim, num_heads=num_heads, qkv_bias=qkv_bias, window_size=window_size)

        self.drop_path = DropPath(drop_path) if drop_path > 0. else nn.Identity()
        mlp_hidden_dim = int(dim * mlp_ratio)
        self.mlp = Mlp(in_features=dim, hidden_features=mlp_hidden_dim, out_features=dim, act_layer=act_layer, drop=drop)
        self.norm2 = norm_layer(dim)

    def forward(self, x):

        x = x + self.drop_path(self.attn(self.norm1(x)))
        x = x + self.drop_path(self.mlp(self.norm2(x)))

        return x


class WF(nn.Module):
    def __init__(self, in_channels=128, decode_channels=128, eps=1e-8):
        super(WF, self).__init__()
        self.pre_conv = Conv(in_channels, decode_channels, kernel_size=1)

        self.weights = nn.Parameter(torch.ones(2, dtype=torch.float32), requires_grad=True)
        self.eps = eps
        self.post_conv = ConvBNReLU(decode_channels, decode_channels, kernel_size=3)

    def forward(self, x, res):
        x = F.interpolate(x, scale_factor=2, mode='bilinear', align_corners=False)
        weights = nn.ReLU()(self.weights)
        fuse_weights = weights / (torch.sum(weights, dim=0) + self.eps)
        x = fuse_weights[0] * self.pre_conv(res) + fuse_weights[1] * x
        x = self.post_conv(x)
        return x


class FeatureRefinementHead(nn.Module):
    def __init__(self, in_channels=64, decode_channels=64):
        super().__init__()
        self.pre_conv = Conv(in_channels, decode_channels, kernel_size=1)

        self.weights = nn.Parameter(torch.ones(2, dtype=torch.float32), requires_grad=True)
        self.eps = 1e-8
        self.post_conv = ConvBNReLU(decode_channels, decode_channels, kernel_size=3)

        self.pa = nn.Sequential(nn.Conv2d(decode_channels, decode_channels, kernel_size=3, padding=1, groups=decode_channels),
                                nn.Sigmoid())
        self.ca = nn.Sequential(nn.AdaptiveAvgPool2d(1),
                                Conv(decode_channels, decode_channels//16, kernel_size=1),
                                nn.ReLU6(),
                                Conv(decode_channels//16, decode_channels, kernel_size=1),
                                nn.Sigmoid())

        self.shortcut = ConvBN(decode_channels, decode_channels, kernel_size=1)
        self.proj = SeparableConvBN(decode_channels, decode_channels, kernel_size=3)
        self.act = nn.ReLU6()

    def forward(self, x, res):
        x = F.interpolate(x, scale_factor=2, mode='bilinear', align_corners=False)
        weights = nn.ReLU()(self.weights)
        fuse_weights = weights / (torch.sum(weights, dim=0) + self.eps)
        x = fuse_weights[0] * self.pre_conv(res) + fuse_weights[1] * x
        x = self.post_conv(x)
        shortcut = self.shortcut(x)
        pa = self.pa(x) * x
        ca = self.ca(x) * x
        x = pa + ca
        x = self.proj(x) + shortcut
        x = self.act(x)

        return x


class AuxHead(nn.Module):

    def __init__(self, in_channels=64, num_classes=8):
        super().__init__()
        self.conv = ConvBNReLU(in_channels, in_channels)
        self.drop = nn.Dropout(0.1)
        self.conv_out = Conv(in_channels, num_classes, kernel_size=1)

    def forward(self, x, h, w):
        feat = self.conv(x)
        feat = self.drop(feat)
        feat = self.conv_out(feat)
        feat = F.interpolate(feat, size=(h, w), mode='bilinear', align_corners=False)
        return feat


class Decoder(nn.Module):
    def __init__(self,
                 encoder_channels=(64, 128, 256, 512),
                 decode_channels=64,
                 dropout=0.1,
                 window_size=8,
                 num_classes=6):
        super(Decoder, self).__init__()

        self.pre_conv = ConvBN(encoder_channels[-1], decode_channels, kernel_size=1)
        self.b4 = Block(dim=decode_channels, num_heads=8, window_size=window_size)

        self.b3 = Block(dim=decode_channels, num_heads=8, window_size=window_size)
        self.p3 = WF(encoder_channels[-2], decode_channels)

        self.b2 = Block(dim=decode_channels, num_heads=8, window_size=window_size)
        self.p2 = WF(encoder_channels[-3], decode_channels)

        if self.training:
            self.up4 = nn.UpsamplingBilinear2d(scale_factor=4)
            self.up3 = nn.UpsamplingBilinear2d(scale_factor=2)
            self.aux_head = AuxHead(decode_channels, num_classes)

        self.p1 = FeatureRefinementHead(encoder_channels[-4], decode_channels)

        self.segmentation_head = nn.Sequential(ConvBNReLU(decode_channels, decode_channels),
                                               nn.Dropout2d(p=dropout, inplace=True),
                                               Conv(decode_channels, num_classes, kernel_size=1))
        self.init_weight()

    def forward(self, res1, res2, res3, res4, h, w):
        if self.training:
            x = self.b4(self.pre_conv(res4))
            h4 = self.up4(x)

            x = self.p3(x, res3)
            x = self.b3(x)
            h3 = self.up3(x)

            x = self.p2(x, res2)
            x = self.b2(x)
            h2 = x
            x = self.p1(x, res1)
            x = self.segmentation_head(x)
            x = F.interpolate(x, size=(h, w), mode='bilinear', align_corners=False)

            ah = h4 + h3 + h2
            ah = self.aux_head(ah, h, w)

            return x, ah
        else:
            x = self.b4(self.pre_conv(res4))
            x = self.p3(x, res3)
            x = self.b3(x)

            x = self.p2(x, res2)
            x = self.b2(x)

            x = self.p1(x, res1)

            x = self.segmentation_head(x)
            x = F.interpolate(x, size=(h, w), mode='bilinear', align_corners=False)

            return x

    def init_weight(self):
        for m in self.children():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, a=1)
                if m.bias is not None:
                    nn.init.constant_(m.bias, 0)


class UNetFormer(nn.Module):
    def __init__(self,
                 decode_channels=64,
                 dropout=0.1,
                 backbone_name='swsl_resnet18',
                 pretrained=True,
                 window_size=8,
                 num_classes=6
                 ):
        super().__init__()

        self.backbone = timm.create_model(backbone_name, features_only=True, output_stride=32,
                                          out_indices=(1, 2, 3, 4), pretrained=pretrained)
        encoder_channels = self.backbone.feature_info.channels()

        self.decoder = Decoder(encoder_channels, decode_channels, dropout, window_size, num_classes)

    def forward(self, x):
        h, w = x.size()[-2:]
        res1, res2, res3, res4 = self.backbone(x)
        if self.training:
            x, ah = self.decoder(res1, res2, res3, res4, h, w)
            return x, ah
        else:
            x = self.decoder(res1, res2, res3, res4, h, w)
            return x

**Decoder block**

**Bottle neck**

**Unet model**

In [13]:
import torch

# Instantiate your UNet model
model = UNetFormer()


# Print the shape of the outputmodel = UNet(n_class=6)

# Create a dummy batch with random images
dummy_batch_size = 16  # Choose your batch size
dummy_input_batch = torch.randn(dummy_batch_size, 3, 256, 256)  # Batch size, 3 channels, 256x256

# Forward pass
output_batch, _ = model(dummy_input_batch)

# Print the shape of the output batch

print("Output batch shape:", output_batch.shape)

/opt/conda/lib/python3.10/site-packages/timm/models/_factory.py:117: UserWarning: Mapping deprecated model name swsl_resnet18 to current resnet18.fb_swsl_ig1b_ft_in1k.
  model = create_fn(


model.safetensors:   0%|          | 0.00/46.8M [00:00<?, ?B/s]

/opt/conda/lib/python3.10/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /usr/local/src/pytorch/aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]


Output batch shape: torch.Size([16, 6, 256, 256])


# Loss function

In [14]:
def label_smoothed_nll_loss(
    lprobs: torch.Tensor, target: torch.Tensor, epsilon: float, ignore_index=None, reduction="mean", dim=-1
) -> torch.Tensor:
    """

    Source: https://github.com/pytorch/fairseq/blob/master/fairseq/criterions/label_smoothed_cross_entropy.py

    :param lprobs: Log-probabilities of predictions (e.g after log_softmax)
    :param target:
    :param epsilon:
    :param ignore_index:
    :param reduction:
    :return:
    """
    if target.dim() == lprobs.dim() - 1:
        target = target.unsqueeze(dim)

    if ignore_index is not None:
        pad_mask = target.eq(ignore_index)
        target = target.masked_fill(pad_mask, 0)
        nll_loss = -lprobs.gather(dim=dim, index=target)
        smooth_loss = -lprobs.sum(dim=dim, keepdim=True)

        # nll_loss.masked_fill_(pad_mask, 0.0)
        # smooth_loss.masked_fill_(pad_mask, 0.0)
        nll_loss = nll_loss.masked_fill(pad_mask, 0.0)
        smooth_loss = smooth_loss.masked_fill(pad_mask, 0.0)
    else:
        nll_loss = -lprobs.gather(dim=dim, index=target)
        smooth_loss = -lprobs.sum(dim=dim, keepdim=True)

        nll_loss = nll_loss.squeeze(dim)
        smooth_loss = smooth_loss.squeeze(dim)

    if reduction == "sum":
        nll_loss = nll_loss.sum()
        smooth_loss = smooth_loss.sum()
    if reduction == "mean":
        nll_loss = nll_loss.mean()
        smooth_loss = smooth_loss.mean()

    eps_i = epsilon / lprobs.size(dim)
    loss = (1.0 - epsilon) * nll_loss + eps_i * smooth_loss
    return loss

In [15]:
__all__ = ["SoftCrossEntropyLoss"]
from typing import Optional
from torch.nn.modules.loss import _Loss
from typing import List
class SoftCrossEntropyLoss(nn.Module):
    """
    Drop-in replacement for nn.CrossEntropyLoss with few additions:
    - Support of label smoothing
    """

    __constants__ = ["reduction", "ignore_index", "smooth_factor"]

    def __init__(self, reduction: str = "mean", smooth_factor: float = 0.0, ignore_index: Optional[int] = -100, dim=1):
        super().__init__()
        self.smooth_factor = smooth_factor
        self.ignore_index = ignore_index
        self.reduction = reduction
        self.dim = dim

    def forward(self, input: Tensor, target: Tensor) -> Tensor:
        log_prob = F.log_softmax(input, dim=self.dim)
        pad_mask = target.eq(self.ignore_index)
        target = target.masked_fill(pad_mask, 0)
        log_prob = log_prob.masked_fill(pad_mask.unsqueeze(1), 0)
        return label_smoothed_nll_loss(
            log_prob,
            target,
            epsilon=self.smooth_factor,
            ignore_index=self.ignore_index,
            reduction=self.reduction,
            dim=self.dim,
        )
__all__ = ["JointLoss", "WeightedLoss"]


class WeightedLoss(_Loss):
    """Wrapper class around loss function that applies weighted with fixed factor.
    This class helps to balance multiple losses if they have different scales
    """

    def __init__(self, loss, weight=1.0):
        super().__init__()
        self.loss = loss
        self.weight = weight

    def forward(self, *input):
        return self.loss(*input) * self.weight
class JointLoss(_Loss):
    """
    Wrap two loss functions into one. This class computes a weighted sum of two losses.
    """

    def __init__(self, first: nn.Module, second: nn.Module, first_weight=1.0, second_weight=1.0):
        super().__init__()
        self.first = WeightedLoss(first, first_weight)
        self.second = WeightedLoss(second, second_weight)

    def forward(self, *input):
        return self.first(*input) + self.second(*input)
__all__ = ["DiceLoss"]

BINARY_MODE = "binary"
MULTICLASS_MODE = "multiclass"
MULTILABEL_MODE = "multilabel"
def soft_dice_score(
    output: torch.Tensor, target: torch.Tensor, smooth: float = 0.0, eps: float = 1e-7, dims=None
) -> torch.Tensor:
    """

    :param output:
    :param target:
    :param smooth:
    :param eps:
    :return:

    Shape:
        - Input: :math:`(N, NC, *)` where :math:`*` means any number
            of additional dimensions
        - Target: :math:`(N, NC, *)`, same shape as the input
        - Output: scalar.

    """
    assert output.size() == target.size()
    if dims is not None:
        intersection = torch.sum(output * target, dim=dims)
        cardinality = torch.sum(output + target, dim=dims)
    else:
        intersection = torch.sum(output * target)
        cardinality = torch.sum(output + target)
    dice_score = (2.0 * intersection + smooth) / (cardinality + smooth).clamp_min(eps)
    return dice_score
class DiceLoss(_Loss):
    """
    Implementation of Dice loss for image segmentation task.
    It supports binary, multiclass and multilabel cases
    """

    def __init__(
        self,
        mode: str = 'multiclass',
        classes: List[int] = None,
        log_loss=False,
        from_logits=True,
        smooth: float = 0.0,
        ignore_index=None,
        eps=1e-7,
    ):
        """

        :param mode: Metric mode {'binary', 'multiclass', 'multilabel'}
        :param classes: Optional list of classes that contribute in loss computation;
        By default, all channels are included.
        :param log_loss: If True, loss computed as `-log(jaccard)`; otherwise `1 - jaccard`
        :param from_logits: If True assumes input is raw logits
        :param smooth:
        :param ignore_index: Label that indicates ignored pixels (does not contribute to loss)
        :param eps: Small epsilon for numerical stability
        """
        assert mode in {BINARY_MODE, MULTILABEL_MODE, MULTICLASS_MODE}
        super(DiceLoss, self).__init__()
        self.mode = mode
        if classes is not None:
            assert mode != BINARY_MODE, "Masking classes is not supported with mode=binary"
            classes = to_tensor(classes, dtype=torch.long)

        self.classes = classes
        self.from_logits = from_logits
        self.smooth = smooth
        self.eps = eps
        self.ignore_index = ignore_index
        self.log_loss = log_loss

    def forward(self, y_pred: Tensor, y_true: Tensor) -> Tensor:
        """

        :param y_pred: NxCxHxW
        :param y_true: NxHxW
        :return: scalar
        """
        assert y_true.size(0) == y_pred.size(0)

        if self.from_logits:
            # Apply activations to get [0..1] class probabilities
            # Using Log-Exp as this gives more numerically stable result and does not cause vanishing gradient on
            # extreme values 0 and 1
            if self.mode == MULTICLASS_MODE:
                y_pred = y_pred.log_softmax(dim=1).exp()
            else:
                y_pred = F.logsigmoid(y_pred).exp()

        bs = y_true.size(0)
        num_classes = y_pred.size(1)
        dims = (0, 2)

        if self.mode == BINARY_MODE:
            y_true = y_true.view(bs, 1, -1)
            y_pred = y_pred.view(bs, 1, -1)

            if self.ignore_index is not None:
                mask = y_true != self.ignore_index
                y_pred = y_pred * mask
                y_true = y_true * mask

        if self.mode == MULTICLASS_MODE:
            y_true = y_true.view(bs, -1)
            y_pred = y_pred.view(bs, num_classes, -1)

            if self.ignore_index is not None:
                mask = y_true != self.ignore_index
                y_pred = y_pred * mask.unsqueeze(1)

                y_true = F.one_hot((y_true * mask).to(torch.long), num_classes)  # N,H*W -> N,H*W, C
                y_true = y_true.permute(0, 2, 1) * mask.unsqueeze(1)  # H, C, H*W
            else:
                y_true = F.one_hot(y_true, num_classes)  # N,H*W -> N,H*W, C
                y_true = y_true.permute(0, 2, 1)  # H, C, H*W

        if self.mode == MULTILABEL_MODE:
            y_true = y_true.view(bs, num_classes, -1)
            y_pred = y_pred.view(bs, num_classes, -1)

            if self.ignore_index is not None:
                mask = y_true != self.ignore_index
                y_pred = y_pred * mask
                y_true = y_true * mask

        scores = soft_dice_score(y_pred, y_true.type_as(y_pred), smooth=self.smooth, eps=self.eps, dims=dims)

        if self.log_loss:
            loss = -torch.log(scores.clamp_min(self.eps))
        else:
            loss = 1.0 - scores

        # Dice loss is undefined for non-empty classes
        # So we zero contribution of channel that does not have true pixels
        # NOTE: A better workaround would be to use loss term `mean(y_pred)`
        # for this case, however it will be a modified jaccard loss

        mask = y_true.sum(dims) > 0
        loss *= mask.to(loss.dtype)

        if self.classes is not None:
            loss = loss[self.classes]

        return loss.mean()


In [16]:

class UnetLoss(nn.Module):
    def __init__(self, ignore_index=255):
        super().__init__()
        self.main_loss = JointLoss(SoftCrossEntropyLoss(smooth_factor=0.05, ignore_index=ignore_index),
                                   DiceLoss(smooth=0.05, ignore_index=ignore_index), 1.0, 1.0)
        self.aux_loss = SoftCrossEntropyLoss(smooth_factor=0.05, ignore_index=ignore_index)

    def forward(self, logits, labels):
        if self.training and len(logits) == 2:
            logit_main, logit_aux = logits
            loss = self.main_loss(logit_main, labels) + 0.4 * self.aux_loss(logit_aux, labels)
        else:
            loss = self.main_loss(logits, labels)

        return loss

# Training

**Initialize weights**

In [17]:
def weights_init(model):
    if isinstance(model, nn.Linear):
        # Xavier Distribution
        torch.nn.init.xavier_uniform_(model.weight)

In [18]:
def save_model(model, optimizer, path):
    checkpoint = {
        "model": model.state_dict(),
        "optimizer": optimizer.state_dict(),
    }
    torch.save(checkpoint, path)

def load_model(model, optimizer, path):
    checkpoint = torch.load(path)
    model.load_state_dict(checkpoint["model"])
    optimizer.load_state_dict(checkpoint['optimizer'])
    return model, optimizer

**Train model**

In [19]:
def train(train_dataloader, valid_dataloader, learing_rate_scheduler, epoch, display_step):
    print(f"Start epoch #{epoch+1}, learning rate for this epoch: {learing_rate_scheduler.get_last_lr()}")
    start_time = time.time()
    train_loss_epoch = 0
    test_loss_epoch = 0
    last_loss = 999999999
    model.train()
    metrics_train = Evaluator(num_class=6)
    metrics_val = Evaluator(num_class=6)

    for i,input in enumerate(tqdm(train_dataloader)):
        # Load data into GPU
        data=input['img']
        masks_true = input['gt_semantic_seg']
        data,mask = data.to(device),masks_true.to(device)
        optimizer.zero_grad()
        prediction, head = model(data)
        # Backpropagation, compute gradients
        loss = loss_function(prediction, mask.long())
        pre_mask = nn.Softmax(dim=1)(prediction)
        pre_mask = pre_mask.argmax(dim=1)
        for i in range(mask.shape[0]):
            metrics_train.add_batch(mask[i].cpu().numpy(), pre_mask[i].cpu().numpy())
        loss.backward()

        # Apply gradients
        optimizer.step()

        # Save loss
        train_loss_epoch += loss.item()
    print(f"Done epoch #{epoch+1}, time for this epoch: {time.time()-start_time}s")
    train_loss_epoch /= (i + 1)
    mIoU = np.nanmean(metrics_train.Intersection_over_Union()[:-1])
    F1 = np.nanmean(metrics_train.F1()[:-1])
    OA = np.nanmean(metrics_train.OA())
    iou_per_class = metrics_train.Intersection_over_Union()
    train_eval_value =  (iou_per_class,mIoU,F1,OA)
    metrics_train.reset()
    # Evaluate the validation set
    model.eval()
    with torch.no_grad():
        for input in tqdm(valid_dataloader):
            data=input['img'].to(device)
            mask = input['gt_semantic_seg'].to(device)
            prediction = model(data)
            test_loss = loss_function(prediction, mask.long())
            pre_mask = nn.Softmax(dim=1)(prediction)
            pre_mask = pre_mask.argmax(dim=1)
            test_loss_epoch += test_loss.item()
            for i in range(mask.shape[0]):
                metrics_val.add_batch(mask[i].cpu().numpy(), pre_mask[i].cpu().numpy())
    test_loss_epoch /= (i + 1)
    mIoU = np.nanmean(metrics_val.Intersection_over_Union()[:-1])
    F1 = np.nanmean(metrics_val.F1()[:-1])
    OA = np.nanmean(metrics_val.OA())
    iou_per_class_val = metrics_val.Intersection_over_Union()
    eval_value =  (iou_per_class_val,mIoU,F1,OA)
    print(eval_value)
    metrics_val.reset()
    return train_loss_epoch, train_eval_value, test_loss_epoch, eval_value


**Test model**

In [20]:

def test(dataloader):
    evaluator = Evaluator(num_class=6)
    evaluator.reset()
    results = []
    for input in tqdm(dataloader):
        # raw_prediction NxCxHxW
        raw_predictions = model(input['img'].cuda())

        image_ids = input["img_id"]
        masks_true = input['gt_semantic_seg']

        raw_predictions = nn.Softmax(dim=1)(raw_predictions)
        predictions = raw_predictions.argmax(dim=1)

        for i in range(raw_predictions.shape[0]):
            mask = predictions[i].cpu().numpy()
            evaluator.add_batch(pre_image=mask, gt_image=masks_true[i].cpu().numpy())
            mask_name = image_ids[i]
            results.append((mask, str(args.output_path / mask_name), args.rgb))
        for i in range(raw_predictions.shape[0]):
            mask = predictions[i].cpu().numpy()
            evaluator.add_batch(pre_image=mask, gt_image=masks_true[i].cpu().numpy())
            mask_name = image_ids[i]
            results.append((mask, str(args.output_path / mask_name), args.rgb))
    iou_per_class = evaluator.Intersection_over_Union()
    f1_per_class = evaluator.F1()
    OA = evaluator.OA()
    return iou_per_class, f1_per_class, OA

In [21]:
device

device(type='cuda')

In [22]:
model = UNetFormer()
model.to(device)

/opt/conda/lib/python3.10/site-packages/timm/models/_factory.py:117: UserWarning: Mapping deprecated model name swsl_resnet18 to current resnet18.fb_swsl_ig1b_ft_in1k.
  model = create_fn(


UNetFormer(
  (backbone): FeatureListNet(
    (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (act1): ReLU(inplace=True)
    (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    (layer1): Sequential(
      (0): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (drop_block): Identity()
        (act1): ReLU(inplace=True)
        (aa): Identity()
        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (act2): ReLU(inplace=True)
      )
      (1): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), p

In [23]:
import torch

# Check if CUDA is available
if torch.cuda.is_available():
    # Use GPU-accelerated PyTorch functions here
    print("CUDA is available.")
else:
    print("CUDA is not available.")

CUDA is available.


In [24]:

loss_function = UnetLoss(ignore_index=6)
# Define the optimizer (Adam optimizer)
optimizer = optim.Adam(params=model.parameters(), lr=learning_rate)
# optimizer.load_state_dict(checkpoint['optimizer'])

# Learning rate scheduler
learing_rate_scheduler = lr_scheduler.StepLR(optimizer, step_size=4, gamma=0.6)

In [25]:
save_model(model, optimizer, checkpoint_path)
load_checkpoint_flag=True

In [26]:
# print("Model keys:")
# print(model.state_dict().keys())

# print("\nCheckpoint keys:")
# print(checkpoint['model'].keys())


In [27]:
# # Load the model checkpoint if needed
# # Load the model checkpoint if needed
# if load_checkpoint_flag:
#     checkpoint = torch.load(checkpoint_path)
#     model, optimize= load_model(model, optimizer, checkpoint)
    


In [28]:
wandb.login(
    # set the wandb project where this run will be logged
#     project= "PolypSegment", 
    key = "b98d2b806f364f5af900550ec98e26e2f418e8a7",
)
wandb.init(
    project = "UnetFormer"
)



wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin
wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: trithuy2003 (deepbk). Use `wandb login --relogin` to force relogin


In [ ]:

# Training loop
train_loss_array = []
test_loss_array = []
last_loss = 9999999999999
for epoch in range(30):
    try:
        train_loss_epoch = 0
        test_loss_epoch = 0
        train_loss_epoch, train_eval_value, test_loss_epoch, eval_value = train(train_loader, 
                                                  val_loader, 
                                                  learing_rate_scheduler, epoch, display_step)

        if test_loss_epoch < last_loss:
            save_model(model, optimizer, checkpoint_path)
            last_loss = test_loss_epoch

        iou_value = {}
        iou_per_class,mIoU,F1,OA=train_eval_value
        eval_value_train = {'mIoU': mIoU,
                          'F1': F1,
                          'OA': OA}                                          
        print('train:', eval_value_train)
        train_accuracy.append(OA)
        wandb.log({'mIoU_train': mIoU,
                          'F1_train': F1,
                          'OA_train': OA}) 

        for class_name, iou in zip(CLASSES,iou_per_class):
            wandb.log({f"{class_name}_train_IOU": iou})
            iou_value[class_name] = iou
        print(iou_value)

        iou_value = {}
        iou_per_class,mIoU,F1,OA = eval_value
        eval_value_val = {'mIoU': mIoU,
                          'F1': F1,
                          'OA': OA}                                          
        print('val:', eval_value_val)
        valid_accuracy.append(OA)
        wandb.log({'mIoU_val': mIoU,
                          'F1_val': F1,
                          'OA_val': OA})
        for class_name, iou in zip(CLASSES,iou_per_class):
            wandb.log({f"{class_name}_val_IoU": iou})
            iou_value[class_name] = iou
        print(iou_value)

        learing_rate_scheduler.step()
        train_loss_array.append(train_loss_epoch)
        test_loss_array.append(test_loss_epoch)
        wandb.log({"Train loss": train_loss_epoch, "Valid loss": test_loss_epoch})
        print("Epoch {}: loss: {:.4f}, train accuracy: {:.4f}, valid accuracy:{:.4f}".format(epoch + 1, 
                                            train_loss_array[-1], train_accuracy[-1], valid_accuracy[-1]))
    except:
        torch.cuda.empty_cache()
    

Start epoch #1, learning rate for this epoch: [0.0008]


100%|██████████| 1785/1785 [09:11<00:00,  3.24it/s]


Done epoch #1, time for this epoch: 551.4718897342682s


100%|██████████| 1786/1786 [01:09<00:00, 25.67it/s]


(array([0.64717044, 0.71061865, 0.57069965, 0.41368214, 0.65190974,
       0.23593554]), 0.5988161221105496, 0.7435691809186342, 0.7378391393266088)
train: {'mIoU': 0.540594107263203, 'F1': 0.7011514982326859, 'OA': 0.6916848030410895}
{'ImSurf': 0.5461696314020782, 'Building': 0.5978403874948474, 'LowVeg': 0.5409975433329953, 'Tree': 0.4909470811297462, 'Car': 0.5270158929563479, 'Clutter': 0.12112995597800702}
val: {'mIoU': 0.5988161221105496, 'F1': 0.7435691809186342, 'OA': 0.7378391393266088}
{'ImSurf': 0.6471704353350934, 'Building': 0.7106186454794262, 'LowVeg': 0.5706996505027185, 'Tree': 0.4136821409247492, 'Car': 0.6519097383107603, 'Clutter': 0.23593554170604347}
Epoch 1: loss: 329.2134, train accuracy: 0.6917, valid accuracy:0.7378
Start epoch #2, learning rate for this epoch: [0.0008]


100%|██████████| 1785/1785 [04:33<00:00,  6.52it/s]


Done epoch #2, time for this epoch: 273.7788314819336s


100%|██████████| 1786/1786 [01:08<00:00, 26.09it/s]


(array([0.68695649, 0.78297078, 0.61983229, 0.50404153, 0.71713906,
       0.29614973]), 0.6621880287955842, 0.7927070636183113, 0.7774214199391732)
train: {'mIoU': 0.6269486900394001, 'F1': 0.7698344353961977, 'OA': 0.7533749128924031}
{'ImSurf': 0.6221480572775675, 'Building': 0.6988513540495006, 'LowVeg': 0.595572858290271, 'Tree': 0.5726324713810115, 'Car': 0.64553870919865, 'Clutter': 0.21106352881208273}
val: {'mIoU': 0.6621880287955842, 'F1': 0.7927070636183113, 'OA': 0.7774214199391732}
{'ImSurf': 0.6869564899064934, 'Building': 0.7829707750703335, 'LowVeg': 0.6198322908245057, 'Tree': 0.5040415322992818, 'Car': 0.7171390558773063, 'Clutter': 0.29614973164879427}
Epoch 2: loss: 282.3474, train accuracy: 0.7534, valid accuracy:0.7774
Start epoch #3, learning rate for this epoch: [0.0008]


100%|██████████| 1785/1785 [04:34<00:00,  6.51it/s]


Done epoch #3, time for this epoch: 274.4078314304352s


100%|██████████| 1786/1786 [01:10<00:00, 25.46it/s]


(array([0.66596357, 0.74524453, 0.63889073, 0.62319052, 0.66973531,
       0.32053565]), 0.6686049314960693, 0.8006497670284904, 0.7898071669383785)
train: {'mIoU': 0.6555176310106046, 'F1': 0.7909305541239025, 'OA': 0.7768019336946205}
{'ImSurf': 0.6527533697869488, 'Building': 0.7395461919631487, 'LowVeg': 0.6202901329673274, 'Tree': 0.6004880609337774, 'Car': 0.6645103994018206, 'Clutter': 0.24660733542412103}
val: {'mIoU': 0.6686049314960693, 'F1': 0.8006497670284904, 'OA': 0.7898071669383785}
{'ImSurf': 0.6659635658330025, 'Building': 0.7452445292812538, 'LowVeg': 0.6388907317095047, 'Tree': 0.6231905190495624, 'Car': 0.6697353116070233, 'Clutter': 0.32053564562515835}
Epoch 3: loss: 265.5068, train accuracy: 0.7768, valid accuracy:0.7898
Start epoch #4, learning rate for this epoch: [0.0008]


100%|██████████| 1785/1785 [04:38<00:00,  6.42it/s]


Done epoch #4, time for this epoch: 278.1174740791321s


 82%|████████▏ | 1472/1786 [00:56<00:11, 27.08it/s]Exception in thread Thread-12 (_pin_memory_loop):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 51, in _pin_memory_loop
    do_one_step()
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 28, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/opt/conda/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/opt/conda/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 307, in rebuild_storage_fd
    fd = df.detach()
  File "/opt/conda/lib/python3.10/multiprocessing/resource_sharer.py", line 58, in detach
    retur

Start epoch #5, learning rate for this epoch: [0.0008]


100%|██████████| 1785/1785 [04:35<00:00,  6.48it/s]


Done epoch #5, time for this epoch: 275.38521790504456s


100%|██████████| 1786/1786 [01:08<00:00, 25.96it/s]


(array([0.7124618 , 0.82842149, 0.67119474, 0.65099929, 0.71837127,
       0.38030143]), 0.7162897166780736, 0.8332444059333295, 0.8243677205651496)
train: {'mIoU': 0.6865965291916514, 'F1': 0.8129960726563905, 'OA': 0.8001853451341474}
{'ImSurf': 0.6855358480493163, 'Building': 0.7820037733492967, 'LowVeg': 0.6446291964394054, 'Tree': 0.626692057593325, 'Car': 0.6941217705269137, 'Clutter': 0.2996642550868076}
val: {'mIoU': 0.7162897166780736, 'F1': 0.8332444059333295, 'OA': 0.8243677205651496}
{'ImSurf': 0.7124617970226633, 'Building': 0.8284214907148536, 'LowVeg': 0.6711947375924444, 'Tree': 0.6509992877394685, 'Car': 0.7183712703209386, 'Clutter': 0.3803014261251818}
Epoch 5: loss: 245.6623, train accuracy: 0.8002, valid accuracy:0.8244
Start epoch #6, learning rate for this epoch: [0.00048]


100%|██████████| 1785/1785 [04:36<00:00,  6.46it/s]


Done epoch #6, time for this epoch: 276.36977338790894s


 80%|████████  | 1437/1786 [00:55<00:13, 26.70it/s]Exception in thread Thread-14 (_pin_memory_loop):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 51, in _pin_memory_loop
    do_one_step()
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 28, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/opt/conda/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/opt/conda/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 307, in rebuild_storage_fd
    fd = df.detach()
  File "/opt/conda/lib/python3.10/multiprocessing/resource_sharer.py", line 58, in detach
    retur

Start epoch #7, learning rate for this epoch: [0.00048]


100%|██████████| 1785/1785 [04:35<00:00,  6.48it/s]


Done epoch #7, time for this epoch: 275.67157340049744s


 77%|███████▋  | 1369/1786 [00:51<00:16, 25.30it/s]Exception in thread Thread-15 (_pin_memory_loop):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 51, in _pin_memory_loop
    do_one_step()
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 28, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/opt/conda/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/opt/conda/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 307, in rebuild_storage_fd
    fd = df.detach()
  File "/opt/conda/lib/python3.10/multiprocessing/resource_sharer.py", line 58, in detach
    retur

Start epoch #8, learning rate for this epoch: [0.00048]


100%|██████████| 1785/1785 [04:37<00:00,  6.43it/s]


Done epoch #8, time for this epoch: 277.4517683982849s


100%|██████████| 1786/1786 [01:09<00:00, 25.55it/s]


(array([0.75350196, 0.87166686, 0.68999635, 0.69742236, 0.75668933,
       0.45588482]), 0.7538553725901965, 0.8581324360825067, 0.8488821804060251)
train: {'mIoU': 0.7261348851328064, 'F1': 0.8400400618981516, 'OA': 0.8302548363095238}
{'ImSurf': 0.727848564377963, 'Building': 0.8335586515884625, 'LowVeg': 0.6770692482843818, 'Tree': 0.6689078209028176, 'Car': 0.7232901405104073, 'Clutter': 0.37950579593068245}
val: {'mIoU': 0.7538553725901965, 'F1': 0.8581324360825067, 'OA': 0.8488821804060251}
{'ImSurf': 0.753501958324994, 'Building': 0.8716668623317019, 'LowVeg': 0.6899963517000502, 'Tree': 0.6974223564462829, 'Car': 0.756689334147954, 'Clutter': 0.4558848200428075}
Epoch 8: loss: 221.4385, train accuracy: 0.8303, valid accuracy:0.8489
Start epoch #9, learning rate for this epoch: [0.00048]


100%|██████████| 1785/1785 [04:38<00:00,  6.41it/s]


Done epoch #9, time for this epoch: 278.67317819595337s


100%|██████████| 1786/1786 [01:09<00:00, 25.62it/s]


(array([0.7563142 , 0.87783405, 0.69264493, 0.69789223, 0.75732643,
       0.45167434]), 0.7564023667075358, 0.8597176962303841, 0.8501161146521159)
train: {'mIoU': 0.7308650771187917, 'F1': 0.8432643422721497, 'OA': 0.8337627710080614}
{'ImSurf': 0.7321848477977775, 'Building': 0.8363093733797895, 'LowVeg': 0.6831072063765126, 'Tree': 0.6744138279951782, 'Car': 0.7283101300447006, 'Clutter': 0.39520749262693095}
val: {'mIoU': 0.7564023667075358, 'F1': 0.8597176962303841, 'OA': 0.8501161146521159}
{'ImSurf': 0.7563142006443715, 'Building': 0.8778340459130101, 'LowVeg': 0.6926449281025869, 'Tree': 0.6978922296110575, 'Car': 0.757326429266653, 'Clutter': 0.45167433945512375}
Epoch 9: loss: 218.7197, train accuracy: 0.8338, valid accuracy:0.8501
Start epoch #10, learning rate for this epoch: [0.00048]


100%|██████████| 1785/1785 [04:34<00:00,  6.50it/s]


Done epoch #10, time for this epoch: 274.7252388000488s


100%|██████████| 1786/1786 [01:08<00:00, 26.02it/s]


(array([0.77715296, 0.87701959, 0.71892974, 0.71457053, 0.76104244,
       0.49203452]), 0.7697430544493062, 0.868681393977264, 0.8634297291387707)
train: {'mIoU': 0.7336651786451073, 'F1': 0.8450460188223957, 'OA': 0.8377188578373244}
{'ImSurf': 0.738216352672059, 'Building': 0.8447732263114057, 'LowVeg': 0.6871891898809406, 'Tree': 0.6771118000981314, 'Car': 0.7210353242629998, 'Clutter': 0.4078479186833989}
val: {'mIoU': 0.7697430544493062, 'F1': 0.868681393977264, 'OA': 0.8634297291387707}
{'ImSurf': 0.7771529649600484, 'Building': 0.8770195945499082, 'LowVeg': 0.7189297442436519, 'Tree': 0.7145705287797236, 'Car': 0.7610424397131992, 'Clutter': 0.49203452402205744}
Epoch 10: loss: 215.7738, train accuracy: 0.8377, valid accuracy:0.8634
Start epoch #11, learning rate for this epoch: [0.00048]


100%|██████████| 1785/1785 [04:34<00:00,  6.49it/s]


Done epoch #11, time for this epoch: 274.8666558265686s


100%|██████████| 1786/1786 [01:11<00:00, 25.03it/s]


(array([0.7771792 , 0.8863131 , 0.72365607, 0.70994828, 0.75280598,
       0.49241453]), 0.7699805241369859, 0.8686747608897308, 0.8639612420219706)
train: {'mIoU': 0.7402537989843484, 'F1': 0.8494116977735257, 'OA': 0.8417173198625153}
{'ImSurf': 0.7432878347529969, 'Building': 0.8519975598034734, 'LowVeg': 0.6938712895482426, 'Tree': 0.6823431601853736, 'Car': 0.7297691506316556, 'Clutter': 0.4122927614734381}
val: {'mIoU': 0.7699805241369859, 'F1': 0.8686747608897308, 'OA': 0.8639612420219706}
{'ImSurf': 0.7771792009223761, 'Building': 0.8863130966269696, 'LowVeg': 0.7236560666862738, 'Tree': 0.7099482784636308, 'Car': 0.7528059779856788, 'Clutter': 0.49241452776448336}
Epoch 11: loss: 212.9324, train accuracy: 0.8417, valid accuracy:0.8640
Start epoch #12, learning rate for this epoch: [0.000288]


100%|██████████| 1785/1785 [04:34<00:00,  6.51it/s]


Done epoch #12, time for this epoch: 274.1070122718811s


 89%|████████▊ | 1585/1786 [01:01<00:07, 27.45it/s]Exception in thread Thread-20 (_pin_memory_loop):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 51, in _pin_memory_loop
    do_one_step()
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 28, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/opt/conda/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/opt/conda/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 307, in rebuild_storage_fd
    fd = df.detach()
  File "/opt/conda/lib/python3.10/multiprocessing/resource_sharer.py", line 58, in detach
    retur

Start epoch #13, learning rate for this epoch: [0.000288]


100%|██████████| 1785/1785 [04:34<00:00,  6.49it/s]


Done epoch #13, time for this epoch: 274.86873960494995s


 91%|█████████ | 1617/1786 [01:01<00:06, 25.68it/s]Exception in thread Thread-21 (_pin_memory_loop):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 51, in _pin_memory_loop
    do_one_step()
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 28, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/opt/conda/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/opt/conda/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 307, in rebuild_storage_fd
    fd = df.detach()
  File "/opt/conda/lib/python3.10/multiprocessing/resource_sharer.py", line 58, in detach
    retur

Start epoch #14, learning rate for this epoch: [0.000288]


100%|██████████| 1785/1785 [04:38<00:00,  6.42it/s]


Done epoch #14, time for this epoch: 278.0883574485779s


100%|██████████| 1786/1786 [01:09<00:00, 25.82it/s]


(array([0.81255937, 0.91184124, 0.74690355, 0.74321714, 0.77669178,
       0.55429505]), 0.7982426145734813, 0.8865202686350842, 0.8836842946693075)
train: {'mIoU': 0.7635132615909561, 'F1': 0.8645353917308787, 'OA': 0.8589094081846605}
{'ImSurf': 0.7714278500516847, 'Building': 0.8782552823877807, 'LowVeg': 0.7141515431924593, 'Tree': 0.7047727137730254, 'Car': 0.7489589185498305, 'Clutter': 0.4700585371746803}
val: {'mIoU': 0.7982426145734813, 'F1': 0.8865202686350842, 'OA': 0.8836842946693075}
{'ImSurf': 0.8125593705729312, 'Building': 0.9118412357077754, 'LowVeg': 0.7469035529343313, 'Tree': 0.7432171363600146, 'Car': 0.7766917772923542, 'Clutter': 0.5542950481265232}
Epoch 14: loss: 197.7244, train accuracy: 0.8589, valid accuracy:0.8837
Start epoch #15, learning rate for this epoch: [0.000288]


100%|██████████| 1785/1785 [04:34<00:00,  6.50it/s]


Done epoch #15, time for this epoch: 274.75355434417725s


 48%|████▊     | 863/1786 [00:32<00:35, 25.83it/s]Exception in thread Thread-23 (_pin_memory_loop):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 51, in _pin_memory_loop
    do_one_step()
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 28, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/opt/conda/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/opt/conda/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 307, in rebuild_storage_fd
    fd = df.detach()
  File "/opt/conda/lib/python3.10/multiprocessing/resource_sharer.py", line 58, in detach
    return

Start epoch #16, learning rate for this epoch: [0.000288]


100%|██████████| 1785/1785 [04:35<00:00,  6.48it/s]


Done epoch #16, time for this epoch: 275.48927092552185s


100%|██████████| 1786/1786 [01:08<00:00, 25.97it/s]


(array([0.81282694, 0.91630555, 0.74634041, 0.74713271, 0.78191453,
       0.56548922]), 0.8009040289727338, 0.8881405451560609, 0.8853412701086546)
train: {'mIoU': 0.7691308654582267, 'F1': 0.8680865045989922, 'OA': 0.8631603326450209}
{'ImSurf': 0.7806693527925266, 'Building': 0.8855827199493183, 'LowVeg': 0.7174800373493293, 'Tree': 0.7092816043947255, 'Car': 0.7526406128052334, 'Clutter': 0.4828864021286697}
val: {'mIoU': 0.8009040289727338, 'F1': 0.8881405451560609, 'OA': 0.8853412701086546}
{'ImSurf': 0.8128269437519686, 'Building': 0.9163055480264367, 'LowVeg': 0.7463404085506512, 'Tree': 0.7471327104111463, 'Car': 0.7819145341234656, 'Clutter': 0.5654892195795875}
Epoch 16: loss: 193.9590, train accuracy: 0.8632, valid accuracy:0.8853
Start epoch #17, learning rate for this epoch: [0.000288]


100%|██████████| 1785/1785 [04:30<00:00,  6.59it/s]


Done epoch #17, time for this epoch: 270.9685437679291s


  9%|▉         | 158/1786 [00:06<01:07, 24.05it/s]Exception in thread Thread-25 (_pin_memory_loop):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 51, in _pin_memory_loop
    do_one_step()
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 28, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/opt/conda/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/opt/conda/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 307, in rebuild_storage_fd
    fd = df.detach()
  File "/opt/conda/lib/python3.10/multiprocessing/resource_sharer.py", line 58, in detach
    return

Start epoch #18, learning rate for this epoch: [0.000288]


100%|██████████| 1785/1785 [04:33<00:00,  6.53it/s]


Done epoch #18, time for this epoch: 273.5017945766449s


 24%|██▍       | 425/1786 [00:17<00:58, 23.32it/s]Exception in thread Thread-26 (_pin_memory_loop):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 51, in _pin_memory_loop
    do_one_step()
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 28, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/opt/conda/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/opt/conda/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 307, in rebuild_storage_fd
    fd = df.detach()
  File "/opt/conda/lib/python3.10/multiprocessing/resource_sharer.py", line 58, in detach
    return

Start epoch #19, learning rate for this epoch: [0.000288]


100%|██████████| 1785/1785 [04:34<00:00,  6.49it/s]


Done epoch #19, time for this epoch: 274.9062123298645s


100%|██████████| 1786/1786 [01:10<00:00, 25.41it/s]


(array([0.8383986 , 0.92530469, 0.7677219 , 0.75831159, 0.79705835,
       0.57961622]), 0.8173590282069055, 0.8983031222198802, 0.8955442539026263)
train: {'mIoU': 0.7768868832351024, 'F1': 0.8731090679231579, 'OA': 0.8696876686160304}
{'ImSurf': 0.789991249673485, 'Building': 0.8904653782144216, 'LowVeg': 0.7300194972693762, 'Tree': 0.7176479575318359, 'Car': 0.7563103334863926, 'Clutter': 0.507344643199719}
val: {'mIoU': 0.8173590282069055, 'F1': 0.8983031222198802, 'OA': 0.8955442539026263}
{'ImSurf': 0.8383986031895411, 'Building': 0.9253046939206796, 'LowVeg': 0.7677219026147167, 'Tree': 0.7583115896779447, 'Car': 0.7970583516316452, 'Clutter': 0.5796162240091093}
Epoch 19: loss: 188.5116, train accuracy: 0.8697, valid accuracy:0.8955
Start epoch #20, learning rate for this epoch: [0.000288]


100%|██████████| 1785/1785 [04:34<00:00,  6.49it/s]


Done epoch #20, time for this epoch: 274.9883089065552s


100%|██████████| 1786/1786 [01:08<00:00, 26.16it/s]


(array([0.83620305, 0.92370827, 0.75491902, 0.69732321, 0.79991272,
       0.5888944 ]), 0.8024132539377933, 0.8883984970686957, 0.8885094564451621)
train: {'mIoU': 0.7815072096647895, 'F1': 0.8760381324031684, 'OA': 0.8729334150041853}
{'ImSurf': 0.7973456012138692, 'Building': 0.894190281021065, 'LowVeg': 0.7336781652818678, 'Tree': 0.7225395389933685, 'Car': 0.7597824618137771, 'Clutter': 0.5155182596492743}
val: {'mIoU': 0.8024132539377933, 'F1': 0.8883984970686957, 'OA': 0.8885094564451621}
{'ImSurf': 0.8362030481301057, 'Building': 0.923708265469095, 'LowVeg': 0.7549190246525108, 'Tree': 0.6973232106596009, 'Car': 0.7999127207776541, 'Clutter': 0.588894402784398}
Epoch 20: loss: 186.0955, train accuracy: 0.8729, valid accuracy:0.8885
Start epoch #21, learning rate for this epoch: [0.0001728]


100%|██████████| 1785/1785 [04:38<00:00,  6.41it/s]


Done epoch #21, time for this epoch: 278.3944413661957s


100%|██████████| 1786/1786 [01:08<00:00, 25.90it/s]


(array([0.85566384, 0.93687806, 0.78623187, 0.77025915, 0.81393998,
       0.62623644]), 0.8325945798023309, 0.907520637804954, 0.9063546439057796)
train: {'mIoU': 0.7915624728543177, 'F1': 0.8823575389458791, 'OA': 0.880038061061827}
{'ImSurf': 0.80888067246605, 'Building': 0.9038247122521507, 'LowVeg': 0.7457354320609211, 'Tree': 0.7308294715702687, 'Car': 0.7685420759221981, 'Clutter': 0.5373466741659053}
val: {'mIoU': 0.8325945798023309, 'F1': 0.907520637804954, 'OA': 0.9063546439057796}
{'ImSurf': 0.8556638448373617, 'Building': 0.9368780579447078, 'LowVeg': 0.7862318678321532, 'Tree': 0.7702591482665625, 'Car': 0.8139399801308693, 'Clutter': 0.6262364354192532}
Epoch 21: loss: 179.9831, train accuracy: 0.8800, valid accuracy:0.9064
Start epoch #22, learning rate for this epoch: [0.0001728]


100%|██████████| 1785/1785 [04:36<00:00,  6.45it/s]


Done epoch #22, time for this epoch: 276.7336368560791s


100%|██████████| 1786/1786 [01:09<00:00, 25.69it/s]


(array([0.78386633, 0.92137781, 0.73436286, 0.72136442, 0.80477352,
       0.60677495]), 0.7931489871399151, 0.8829435056554399, 0.8777681599225533)
train: {'mIoU': 0.793952331582995, 'F1': 0.883857756638674, 'OA': 0.8824454128575259}
{'ImSurf': 0.8144667526678392, 'Building': 0.9052412145822293, 'LowVeg': 0.7480864384667013, 'Tree': 0.735239915625608, 'Car': 0.7667273365725973, 'Clutter': 0.5409262318219472}
val: {'mIoU': 0.7931489871399151, 'F1': 0.8829435056554399, 'OA': 0.8777681599225533}
{'ImSurf': 0.7838663302410728, 'Building': 0.9213778104288045, 'LowVeg': 0.7343628554373318, 'Tree': 0.7213644158156041, 'Car': 0.8047735237767621, 'Clutter': 0.6067749487163149}
Epoch 22: loss: 178.3413, train accuracy: 0.8824, valid accuracy:0.8778
Start epoch #23, learning rate for this epoch: [0.0001728]


100%|██████████| 1785/1785 [04:34<00:00,  6.49it/s]


Done epoch #23, time for this epoch: 274.9800503253937s


100%|██████████| 1786/1786 [01:10<00:00, 25.47it/s]


(array([0.8547282 , 0.93242003, 0.79088023, 0.77572259, 0.81718607,
       0.64162798]), 0.8341874227947847, 0.9086058253136375, 0.907828142101638)
train: {'mIoU': 0.7962129715689741, 'F1': 0.8853136607151317, 'OA': 0.8835606230407201}
{'ImSurf': 0.815649647999906, 'Building': 0.9052354998476483, 'LowVeg': 0.7508549707901694, 'Tree': 0.7374770741954951, 'Car': 0.7718476650116518, 'Clutter': 0.5513167126675064}
val: {'mIoU': 0.8341874227947847, 'F1': 0.9086058253136375, 'OA': 0.907828142101638}
{'ImSurf': 0.854728195935228, 'Building': 0.9324200259501334, 'LowVeg': 0.7908802328740326, 'Tree': 0.7757225903163334, 'Car': 0.8171860688981968, 'Clutter': 0.6416279819462759}
Epoch 23: loss: 176.8945, train accuracy: 0.8836, valid accuracy:0.9078
Start epoch #24, learning rate for this epoch: [0.0001728]


100%|██████████| 1785/1785 [04:34<00:00,  6.51it/s]


Done epoch #24, time for this epoch: 274.0754771232605s


100%|██████████| 1786/1786 [01:07<00:00, 26.30it/s]


(array([0.86084165, 0.94044206, 0.7909469 , 0.77956462, 0.81461629,
       0.64109085]), 0.8372823029376579, 0.9103530136274035, 0.9098842860954128)
train: {'mIoU': 0.7994894869076372, 'F1': 0.8873715762847073, 'OA': 0.8857667116223931}
{'ImSurf': 0.8198502708602281, 'Building': 0.9068447955242497, 'LowVeg': 0.7555959541890718, 'Tree': 0.7401283620803965, 'Car': 0.77502805188424, 'Clutter': 0.5622137054797453}
val: {'mIoU': 0.8372823029376579, 'F1': 0.9103530136274035, 'OA': 0.9098842860954128}
{'ImSurf': 0.8608416523625688, 'Building': 0.9404420570012431, 'LowVeg': 0.7909469034833378, 'Tree': 0.7795646153931205, 'Car': 0.81461628644802, 'Clutter': 0.6410908459691866}
Epoch 24: loss: 174.6396, train accuracy: 0.8858, valid accuracy:0.9099
Start epoch #25, learning rate for this epoch: [0.00010368]


100%|██████████| 1785/1785 [04:35<00:00,  6.48it/s]


Done epoch #25, time for this epoch: 275.44224643707275s


100%|██████████| 1786/1786 [01:08<00:00, 26.17it/s]


(array([0.85152685, 0.94012699, 0.78576824, 0.77670879, 0.82632145,
       0.65781226]), 0.8360904647377861, 0.909641912985153, 0.9083050040982396)
train: {'mIoU': 0.8057286738160488, 'F1': 0.8912441914171414, 'OA': 0.8898877034334242}
{'ImSurf': 0.8263052557327849, 'Building': 0.911875047381227, 'LowVeg': 0.7626787007392369, 'Tree': 0.7461537323280537, 'Car': 0.7816306328989413, 'Clutter': 0.5773976178079925}
val: {'mIoU': 0.8360904647377861, 'F1': 0.909641912985153, 'OA': 0.9083050040982396}
{'ImSurf': 0.8515268542443085, 'Building': 0.9401269867075043, 'LowVeg': 0.7857682424420426, 'Tree': 0.7767087948032813, 'Car': 0.8263214454917945, 'Clutter': 0.657812260886745}
Epoch 25: loss: 171.9145, train accuracy: 0.8899, valid accuracy:0.9083
Start epoch #26, learning rate for this epoch: [0.00010368]


100%|██████████| 1785/1785 [04:37<00:00,  6.43it/s]


Done epoch #26, time for this epoch: 277.4007785320282s


100%|██████████| 1786/1786 [01:10<00:00, 25.47it/s]


(array([0.86622485, 0.94372893, 0.79517555, 0.78722314, 0.82677868,
       0.66295026]), 0.8438262305636435, 0.9142785450288873, 0.9136592696997196)
train: {'mIoU': 0.8082950927838082, 'F1': 0.8928028281486219, 'OA': 0.8921734101965981}
{'ImSurf': 0.8313174676217066, 'Building': 0.914220935139945, 'LowVeg': 0.7654241439390044, 'Tree': 0.7473759801254414, 'Car': 0.7831369370929444, 'Clutter': 0.5849494410564202}
val: {'mIoU': 0.8438262305636435, 'F1': 0.9142785450288873, 'OA': 0.9136592696997196}
{'ImSurf': 0.8662248505044983, 'Building': 0.9437289312899806, 'LowVeg': 0.795175551110603, 'Tree': 0.7872231357825802, 'Car': 0.8267786841305558, 'Clutter': 0.6629502599650923}
Epoch 26: loss: 170.2574, train accuracy: 0.8922, valid accuracy:0.9137
Start epoch #27, learning rate for this epoch: [0.00010368]


100%|██████████| 1785/1785 [04:37<00:00,  6.43it/s]


Done epoch #27, time for this epoch: 277.73217606544495s


100%|██████████| 1786/1786 [01:09<00:00, 25.55it/s]


(array([0.87280447, 0.94359307, 0.80557876, 0.78407439, 0.82768522,
       0.65875172]), 0.8467471822969035, 0.9160145947089834, 0.9158045146375663)
train: {'mIoU': 0.8101016671341034, 'F1': 0.8938657407097838, 'OA': 0.8929503058852936}
{'ImSurf': 0.8332149939796811, 'Building': 0.9173426057044046, 'LowVeg': 0.7654518273682722, 'Tree': 0.7461517568949748, 'Car': 0.7883471517231844, 'Clutter': 0.5837642228856629}
val: {'mIoU': 0.8467471822969035, 'F1': 0.9160145947089834, 'OA': 0.9158045146375663}
{'ImSurf': 0.8728044713329972, 'Building': 0.9435930737899464, 'LowVeg': 0.8055787588391394, 'Tree': 0.784074392228916, 'Car': 0.8276852152935182, 'Clutter': 0.6587517196231988}
Epoch 27: loss: 169.3184, train accuracy: 0.8930, valid accuracy:0.9158
Start epoch #28, learning rate for this epoch: [0.00010368]


100%|██████████| 1785/1785 [04:34<00:00,  6.50it/s]


Done epoch #28, time for this epoch: 274.4540774822235s


 42%|████▏     | 750/1786 [00:28<00:42, 24.61it/s]Exception in thread Thread-36 (_pin_memory_loop):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 51, in _pin_memory_loop
    do_one_step()
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 28, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/opt/conda/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/opt/conda/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 307, in rebuild_storage_fd
    fd = df.detach()
  File "/opt/conda/lib/python3.10/multiprocessing/resource_sharer.py", line 58, in detach
    return

Start epoch #29, learning rate for this epoch: [0.00010368]


 10%|█         | 182/1785 [00:28<03:47,  7.05it/s]

In [ ]:
torch.cuda.empty_cache()

# Plot the learning cure

In [ ]:
# load_model(model, checkpoint)

In [ ]:
plt.rcParams['figure.dpi'] = 90
plt.rcParams['figure.figsize'] = (6, 4)
epochs_array = range(epochs)

In [ ]:
# Plot Training and Test loss
plt.plot(epochs_array, train_loss_array, 'g', label='Training loss')
plt.plot(epochs_array, test_loss_array, 'b', label='Test loss')
plt.title('Training and Test loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.show()

**Infer**

In [ ]:
# from torch.jit import load
# model = UNet()
# optimizer = optim.Adam(params=model.parameters(), lr=learning_rate)

# checkpoint = torch.load(pretrained_path)

In [ ]:
# optimizer.load_state_dict(checkpoint['optimizer'])

In [ ]:
# from collections import OrderedDict
# new_state_dict = OrderedDict()
# for k, v in checkpoint['model'].items():
#     name = k[7:] # remove `module.`
#     new_state_dict[name] = v
# # load params
# model.load_state_dict(new_state_dict)

**Visualize results**

In [ ]:
for i, (data, label) in enumerate(train_dataloader):
    img = data
    mask = label
    break

In [ ]:
# fig, arr = plt.subplots(4, 3, figsize=(16, 12))
# arr[0][0].set_title('Image')
# arr[0][1].set_title('Segmentation')
# arr[0][2].set_title('Predict')

# model.eval()
# with torch.no_grad():
#     z = img.to(device)
#     predict = model(z)

# def display_image_grid(images_filenames, images_directory, masks_directory, predicted_masks=None):
#     cols = 3 if predicted_masks else 2
#     rows = len(images_filenames)
#     figure, ax = plt.subplots(nrows=rows, ncols=cols, figsize=(10, 24))
#     for i, image_filename in enumerate(images_filenames):
#         image = cv2.imread(os.path.join(images_directory, image_filename))
#         image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

#         mask = cv2.imread(os.path.join(masks_directory, image_filename.replace(".jpeg", ".png")), cv2.IMREAD_UNCHANGED,)
#         mask = preprocess_mask(mask)
#         ax[i, 0].imshow(image)
#         ax[i, 1].imshow(mask, interpolation="nearest")

#         ax[i, 0].set_title("Image")
#         ax[i, 1].set_title("Ground truth mask")

#         ax[i, 0].set_axis_off()
#         ax[i, 1].set_axis_off()

#         if predicted_masks:
#             predicted_mask = predicted_masks[i]
#             ax[i, 2].imshow(predicted_mask, interpolation="nearest")
#             ax[i, 2].set_title("Predicted mask")
#             ax[i, 2].set_axis_off()
#     plt.tight_layout()
#     plt.show()

# display_image_grid(, images_directory, masks_directory,predicted_masks = predict)    
# # for i in range(2):
# #     arr[i][0].imshow(img[i].permute(1, 2, 0));
    
# #     arr[i][1].imshow(F.one_hot(mask[i]).float())
    
# #     arr[i][2].imshow(F.one_hot(torch.argmax(predict[i], 0).cpu()).float())

**Create submission**

In [ ]:
def seed_everything(seed):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = True

In [ ]:
def img_writer(inp):
    (mask,  mask_id, rgb) = inp
    if rgb:
        mask_name_tif = mask_id + '.png'
        mask_tif = label2rgb(mask)
        cv2.imwrite(mask_name_tif, mask_tif)
    else:
        mask_png = mask.astype(np.uint8)
        mask_name_png = mask_id + '.png'
        cv2.imwrite(mask_name_png, mask_png)


def get_args():
    parser = argparse.ArgumentParser()
    arg = parser.add_argument
    arg("-c", "--config_path", type=Path, required=True, help="Path to  config")
    arg("-o", "--output_path", type=Path, help="Path where to save resulting masks.", required=True)
    arg("-t", "--tta", help="Test time augmentation.", default=None, choices=[None, "d4", "lr"])
    arg("--rgb", help="whether output rgb images", action='store_true')
    return parser.parse_args()

In [ ]:
args = get_args()
seed_everything(42)

config = py2cfg(args.config_path)
args.output_path.mkdir(exist_ok=True, parents=True)

model = Supervision_Train.load_from_checkpoint(
    os.path.join(config.weights_path, config.test_weights_name + '.ckpt'), config=config)
model.cuda()
model.eval()
evaluator = Evaluator(num_class=config.num_classes)
evaluator.reset()
if args.tta == "lr":
    transforms = tta.Compose(
        [
            tta.HorizontalFlip(),
            tta.VerticalFlip()
        ]
    )
    model = tta.SegmentationTTAWrapper(model, transforms)
elif args.tta == "d4":
    transforms = tta.Compose(
        [
            tta.HorizontalFlip(),
            tta.VerticalFlip(),
            # tta.Rotate90(angles=[90]),
            tta.Scale(scales=[0.75, 1.0, 1.25, 1.5], interpolation='bicubic', align_corners=False)
        ]
    )
    model = tta.SegmentationTTAWrapper(model, transforms)

test_dataset = config.test_dataset

with torch.no_grad():
    test_loader = DataLoader(
        test_dataset,
        batch_size=2,
        num_workers=4,
        pin_memory=True,
        drop_last=False,
    )
    results = []
    for input in tqdm(test_loader):
        # raw_prediction NxCxHxW
        raw_predictions, _ = model(input['img'].cuda())

        image_ids = input["img_id"]
        masks_true = input['gt_semantic_seg']

        raw_predictions, _ = nn.Softmax(dim=1)(raw_predictions)
        predictions = raw_predictions.argmax(dim=1)

        for i in range(raw_predictions.shape[0]):
            mask = predictions[i].cpu().numpy()
            evaluator.add_batch(pre_image=mask, gt_image=masks_true[i].cpu().numpy())
            mask_name = image_ids[i]
            results.append((mask, str(args.output_path / mask_name), args.rgb))
iou_per_class = evaluator.Intersection_over_Union()
f1_per_class = evaluator.F1()
OA = evaluator.OA()
for class_name, class_iou, class_f1 in zip(CLASSES, iou_per_class, f1_per_class):
    print('F1_{}:{}, IOU_{}:{}'.format(class_name, class_f1, class_name, class_iou))
print('F1:{}, mIOU:{}, OA:{}'.format(np.nanmean(f1_per_class[:-1]), np.nanmean(iou_per_class[:-1]), OA))
t0 = time.time()
mpp.Pool(processes=mp.cpu_count()).map(img_writer, results)
t1 = time.time()
img_write_time = t1 - t0
print('images writing spends: {} s'.format(img_write_time))



In [ ]:
transform = A.Compose([A.Resize(384, 384),
                       A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
                     ToTensorV2(),])

In [ ]:
# fig, arr = plt.subplots(5, 2, figsize=(16, 12))
# arr[0][0].set_title('Image');
# arr[0][1].set_title('Predict');

# model.eval()
# with torch.no_grad():
#     z = img.to(device)
#     predict = model(z)

# for i in range(5):
#     arr[i][0].imshow(img[i].permute(1, 2, 0));
#     arr[i][1].imshow(F.one_hot(torch.argmax(predict[i], 0).cpu()).float())

In [ ]:
model.eval()
if not os.path.isdir("/kaggle/working/predicted_masks"):
    os.mkdir("/kaggle/working/predicted_masks")
for _, (img, path, H, W) in enumerate(test_dataloader):
    a = path
    b = img
    h = H
    w = W
    
    with torch.no_grad():
        z = b.to(device)
        predicted_mask = model(z)
    for i in range(len(a)):
        image_id = a[i].split('/')[-1].split('.')[0]
        filename = image_id + ".png"
        mask2img = Resize((h[i].item(), w[i].item()), interpolation=InterpolationMode.NEAREST)(ToPILImage()(F.one_hot(torch.argmax(predicted_mask[i], 0)).permute(2, 0, 1).float()))
        mask2img.save(os.path.join("/kaggle/working/predicted_masks/", filename))

In [ ]:
def rle_to_string(runs):
    return ' '.join(str(x) for x in runs)

def rle_encode_one_mask(mask):
    pixels = mask.flatten()
    pixels[pixels > 0] = 255
    use_padding = False
    if pixels[0] or pixels[-1]:
        use_padding = True
        pixel_padded = np.zeros([len(pixels) + 2], dtype=pixels.dtype)
        pixel_padded[1:-1] = pixels
        pixels = pixel_padded
    
    rle = np.where(pixels[1:] != pixels[:-1])[0] + 2
    if use_padding:
        rle = rle - 1
    rle[1::2] = rle[1::2] - rle[:-1:2]
    return rle_to_string(rle)

def mask2string(dir):
    ## mask --> string
    strings = []
    ids = []
    ws, hs = [[] for i in range(2)]
    for image_id in os.listdir(dir):
        id = image_id.split('.')[0]
        path = os.path.join(dir, image_id)
        print(path)
        img = cv2.imread(path)[:,:,::-1]
        h, w = img.shape[0], img.shape[1]
        for channel in range(2):
            ws.append(w)
            hs.append(h)
            ids.append(f'{id}_{channel}')
            string = rle_encode_one_mask(img[:,:,channel])
            strings.append(string)
    r = {
        'ids': ids,
        'strings': strings,
    }
    return r


MASK_DIR_PATH = '/kaggle/working/predicted_masks' # change this to the path to your output mask folder
dir = MASK_DIR_PATH
res = mask2string(dir)
df = pd.DataFrame(columns=['Id', 'Expected'])
df['Id'] = res['ids']
df['Expected'] = res['strings']
df.to_csv(r'output.csv', index=False)