In [1]:

!pip install torchgeometry


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.7/42.7 kB 3.7 MB/s eta 0:00:00


In [2]:
!pip show torch


Name: torch
Version: 2.0.0
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /opt/conda/lib/python3.10/site-packages
Requires: filelock, jinja2, networkx, sympy, typing-extensions
Required-by: accelerate, catalyst, easyocr, fastai, kornia, pytorch-ignite, pytorch-lightning, stable-baselines3, timm, torchaudio, torchdata, torchgeometry, torchmetrics, torchtext, torchvision


In [3]:

# from torchgeometry.losses import one_hot
import os
import os.path as osp
import pandas as pd
import numpy as np
from PIL import Image
import cv2
import time
import imageio
import matplotlib.pyplot as plt
import time
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.optim import lr_scheduler
from torch import Tensor
from torch.utils.data import Dataset, DataLoader, random_split
from torchvision.transforms import Resize, PILToTensor, ToPILImage, Compose, InterpolationMode
from collections import OrderedDict
import wandb
import albumentations as A
from albumentations.pytorch.transforms import ToTensorV2
import glob
import multiprocessing.pool as mpp
import multiprocessing as mp
import argparse
import torch
import albumentations as albu
from torchvision.transforms import (Pad, ColorJitter, Resize, FiveCrop, RandomResizedCrop,
                                    RandomHorizontalFlip, RandomRotation, RandomVerticalFlip)
import random
import math
import numbers
from PIL import Image, ImageOps, ImageEnhance
import numpy as np
import random
from scipy.ndimage.morphology import generate_binary_structure, binary_erosion
from scipy.ndimage import maximum_filter
from tqdm import tqdm
import pytorch_lightning as pl
# from pytorch_lightning.callbacks import Model
import os
import torch
from torch import nn
import cv2
import numpy as np
import argparse
from pathlib import Path

from pytorch_lightning.loggers import CSVLogger
import random

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [4]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

# Parameters

In [5]:

num_classes = 6

# Number of epoch
epochs = 25

# Hyperparameters for training 
learning_rate = 1e-03
batch_size = 16
display_step = 2

# Model path
checkpoint_path = '/kaggle/working/unetplusplus_tune.pth'
pretrained_path = "/kaggle/input/model2/unet_model.pth"
# Initialize lists to keep track of loss and accuracy
loss_epoch_array = []
train_accuracy = []
test_accuracy = []
valid_accuracy = []

In [6]:
SEED = 42


def seed_everything(seed):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = True
seed_everything(42)

ImSurf = np.array([255, 255, 255])  # label 0
Building = np.array([255, 0, 0]) # label 1
LowVeg = np.array([255, 255, 0]) # label 2
Tree = np.array([0, 255, 0]) # label 3
Car = np.array([0, 255, 255]) # label 4
Clutter = np.array([0, 0, 255]) # label 5
Boundary = np.array([0, 0, 0]) # label 6
num_classes = 6





def pv2rgb(mask):
    h, w = mask.shape[0], mask.shape[1]
    mask_rgb = np.zeros(shape=(h, w, 3), dtype=np.uint8)
    mask_convert = mask[np.newaxis, :, :]
    mask_rgb[np.all(mask_convert == 3, axis=0)] = [0, 255, 0]
    mask_rgb[np.all(mask_convert == 0, axis=0)] = [255, 255, 255]
    mask_rgb[np.all(mask_convert == 1, axis=0)] = [255, 0, 0]
    mask_rgb[np.all(mask_convert == 2, axis=0)] = [255, 255, 0]
    mask_rgb[np.all(mask_convert == 4, axis=0)] = [0, 204, 255]
    mask_rgb[np.all(mask_convert == 5, axis=0)] = [0, 0, 255]
    return mask_rgb
def label2rgb(mask):
    h, w = mask.shape[0], mask.shape[1]
    mask_rgb = np.zeros(shape=(h, w, 3), dtype=np.uint8)
    mask_convert = mask[np.newaxis, :, :]
    mask_rgb[np.all(mask_convert == 3, axis=0)] = [0, 255, 0]
    mask_rgb[np.all(mask_convert == 0, axis=0)] = [255, 255, 255]
    mask_rgb[np.all(mask_convert == 1, axis=0)] = [255, 0, 0]
    mask_rgb[np.all(mask_convert == 2, axis=0)] = [255, 255, 0]
    mask_rgb[np.all(mask_convert == 4, axis=0)] = [0, 204, 255]
    mask_rgb[np.all(mask_convert == 5, axis=0)] = [0, 0, 255]
    return mask_rgb



def car_color_replace(mask):
    mask = cv2.cvtColor(np.array(mask.copy()), cv2.COLOR_RGB2BGR)
    mask[np.all(mask == [0, 255, 255], axis=-1)] = [0, 204, 255]

    return mask


def rgb_to_2D_label(_label):
    _label = _label.transpose(2, 0, 1)
    label_seg = np.zeros(_label.shape[1:], dtype=np.uint8)
    label_seg[np.all(_label.transpose([1, 2, 0]) == ImSurf, axis=-1)] = 0
    label_seg[np.all(_label.transpose([1, 2, 0]) == Building, axis=-1)] = 1
    label_seg[np.all(_label.transpose([1, 2, 0]) == LowVeg, axis=-1)] = 2
    label_seg[np.all(_label.transpose([1, 2, 0]) == Tree, axis=-1)] = 3
    label_seg[np.all(_label.transpose([1, 2, 0]) == Car, axis=-1)] = 4
    label_seg[np.all(_label.transpose([1, 2, 0]) == Clutter, axis=-1)] = 5
    label_seg[np.all(_label.transpose([1, 2, 0]) == Boundary, axis=-1)] = 6
    return label_seg



    

 # Split Data

 # Dataloader

In [7]:
CLASSES = ('ImSurf', 'Building', 'LowVeg', 'Tree', 'Car', 'Clutter')
class_label={0:'ImSurf', 1:'Building',2: 'LowVeg', 3:'Tree', 4:'Car',5: 'Clutter'}
PALETTE = [[255, 255, 255], [0, 0, 255], [0, 255, 255], [0, 255, 0], [255, 204, 0], [255, 0, 0]]

ORIGIN_IMG_SIZE = (256, 256)
INPUT_IMG_SIZE = (256, 256)
TEST_IMG_SIZE = (256, 256)

def get_training_transform():
    train_transform = [
        # albu.RandomBrightnessContrast(brightness_limit=0.25, contrast_limit=0.25, p=0.15),
        # albu.RandomRotate90(p=0.25),
        albu.Normalize()
    ]
    return albu.Compose(train_transform)

def get_val_transform():
    val_transform = [
        albu.RandomRotate90(p=0.5),
        albu.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, p=0.5),
        albu.Normalize()
    ]
    return albu.Compose(val_transform)


def val_aug(img, mask):
    img, mask = np.array(img), np.array(mask)
    aug = get_val_transform()(image=img.copy(), mask=mask.copy())
    img, mask = aug['image'], aug['mask']
    return img, mask


class PotsdamDataset(Dataset):
    def __init__(self, data_root='/kaggle/input/deep-data-potsdam-vaihingen/Deep_data_segmentation/Split/Potsdam/', mode='val', img_dir='Image', mask_dir='Label/',
                 img_suffix='.tif', mask_suffix='.png', transform=val_aug, mosaic_ratio=0.0,
                 img_size=ORIGIN_IMG_SIZE):
        self.data_root = data_root
        self.img_dir = img_dir
        self.mask_dir = mask_dir
        self.img_suffix = img_suffix
        self.mask_suffix = mask_suffix
        self.transform = transform
        self.mode = mode
        self.mosaic_ratio = mosaic_ratio
        self.img_size = img_size
        self.img_ids = self.get_img_ids(self.data_root, self.img_dir, self.mask_dir)

    def __getitem__(self, index):
        p_ratio = random.random()
        if p_ratio > self.mosaic_ratio or self.mode == 'val' or self.mode == 'test':
            img, mask = self.load_img_and_mask(index)
            if self.transform:
                img, mask = self.transform(img, mask)
        else:
            img, mask = self.load_mosaic_img_and_mask(index)
            if self.transform:
                img, mask = self.transform(img, mask)

        img = torch.from_numpy(img).permute(2, 0, 1).float()
        mask = torch.from_numpy(mask).long()
        img_id = self.img_ids[index]
        results = dict(img_id=img_id, img=img, gt_semantic_seg=mask)
        return results

    def __len__(self):
        return len(self.img_ids)

    def get_img_ids(self, data_root, img_dir, mask_dir):
        img_filename_list = os.listdir(osp.join(data_root, img_dir))
        mask_filename_list = os.listdir(osp.join(data_root, mask_dir))
        assert len(img_filename_list) == len(mask_filename_list)
        img_ids = [str(id.split('.')[0]) for id in mask_filename_list]
        return img_ids

    def load_img_and_mask(self, index):
        img_id = self.img_ids[index]
        img_name = osp.join(self.data_root, self.img_dir, img_id + self.img_suffix)
        mask_name = osp.join(self.data_root, self.mask_dir, img_id + self.mask_suffix)
        img = Image.open(img_name).convert('RGB')
        mask = Image.open(mask_name).convert('L')
        return img, mask

    def load_mosaic_img_and_mask(self, index):
        indexes = [index] + [random.randint(0, len(self.img_ids) - 1) for _ in range(3)]
        img_a, mask_a = self.load_img_and_mask(indexes[0])
        img_b, mask_b = self.load_img_and_mask(indexes[1])
        img_c, mask_c = self.load_img_and_mask(indexes[2])
        img_d, mask_d = self.load_img_and_mask(indexes[3])

        img_a, mask_a = np.array(img_a), np.array(mask_a)
        img_b, mask_b = np.array(img_b), np.array(mask_b)
        img_c, mask_c = np.array(img_c), np.array(mask_c)
        img_d, mask_d = np.array(img_d), np.array(mask_d)

        w = self.img_size[1]
        h = self.img_size[0]

        start_x = w // 4
        strat_y = h // 4
        # The coordinates of the splice center
        offset_x = random.randint(start_x, (w - start_x))
        offset_y = random.randint(strat_y, (h - strat_y))

        crop_size_a = (offset_x, offset_y)
        crop_size_b = (w - offset_x, offset_y)
        crop_size_c = (offset_x, h - offset_y)
        crop_size_d = (w - offset_x, h - offset_y)

        random_crop_a = albu.RandomCrop(width=crop_size_a[0], height=crop_size_a[1])
        random_crop_b = albu.RandomCrop(width=crop_size_b[0], height=crop_size_b[1])
        random_crop_c = albu.RandomCrop(width=crop_size_c[0], height=crop_size_c[1])
        random_crop_d = albu.RandomCrop(width=crop_size_d[0], height=crop_size_d[1])

        croped_a = random_crop_a(image=img_a.copy(), mask=mask_a.copy())
        croped_b = random_crop_b(image=img_b.copy(), mask=mask_b.copy())
        croped_c = random_crop_c(image=img_c.copy(), mask=mask_c.copy())
        croped_d = random_crop_d(image=img_d.copy(), mask=mask_d.copy())

        img_crop_a, mask_crop_a = croped_a['image'], croped_a['mask']
        img_crop_b, mask_crop_b = croped_b['image'], croped_b['mask']
        img_crop_c, mask_crop_c = croped_c['image'], croped_c['mask']
        img_crop_d, mask_crop_d = croped_d['image'], croped_d['mask']

        top = np.concatenate((img_crop_a, img_crop_b), axis=1)
        bottom = np.concatenate((img_crop_c, img_crop_d), axis=1)
        img = np.concatenate((top, bottom), axis=0)

        top_mask = np.concatenate((mask_crop_a, mask_crop_b), axis=1)
        bottom_mask = np.concatenate((mask_crop_c, mask_crop_d), axis=1)
        mask = np.concatenate((top_mask, bottom_mask), axis=0)
        mask = np.ascontiguousarray(mask)
        img = np.ascontiguousarray(img)

        img = Image.fromarray(img)
        mask = Image.fromarray(mask)

        return img, mask

In [8]:

train_dataset = PotsdamDataset(data_root='/kaggle/input/deep-data-potsdam-vaihingen/Deep_data_segmentation/Split/Potsdam/', mode='train',
                               mosaic_ratio=0.25, transform=val_aug)

train_size = 0.35
valid_size = 0.65
dumb1 = 0.15
dumb2 = 0.85
train_length = round(train_size * len(train_dataset))
valid_length = round(valid_size * len(train_dataset))
train_set, dumb0 = random_split(train_dataset, [train_length, valid_length])
val_set, xxx = random_split(dumb0, [dumb1, dumb2])


test_dataset = PotsdamDataset(data_root='/kaggle/input/deep-data-potsdam-vaihingen/Deep_data_segmentation/Split/Potsdam/Test',
                              transform=val_aug)

train_loader = DataLoader(dataset=train_set,
                          batch_size=batch_size,
                          num_workers=0,
                          pin_memory=False,
                          shuffle=True,
                          drop_last=True
                         )

val_loader = DataLoader(dataset=val_set,
                        batch_size=batch_size,
                        num_workers=2,
                        shuffle=False,
                        pin_memory=True,
                        drop_last=False)


# Metric

In [9]:
class Evaluator(object):
    def __init__(self, num_class):
        self.num_class = num_class
        self.confusion_matrix = np.zeros((self.num_class,) * 2)
        self.eps = 1e-8

    def get_tp_fp_tn_fn(self):
        tp = np.diag(self.confusion_matrix)
        fp = self.confusion_matrix.sum(axis=0) - np.diag(self.confusion_matrix)
        fn = self.confusion_matrix.sum(axis=1) - np.diag(self.confusion_matrix)
        tn = np.diag(self.confusion_matrix).sum() - np.diag(self.confusion_matrix)
        return tp, fp, tn, fn

    def Precision(self):
        tp, fp, tn, fn = self.get_tp_fp_tn_fn()
        precision = tp / (tp + fp)
        return precision

    def Recall(self):
        tp, fp, tn, fn = self.get_tp_fp_tn_fn()
        recall = tp / (tp + fn)
        return recall

    def F1(self):
        tp, fp, tn, fn = self.get_tp_fp_tn_fn()
        Precision = tp / (tp + fp)
        Recall = tp / (tp + fn)
        F1 = (2.0 * Precision * Recall) / (Precision + Recall)
        return F1

    def OA(self):
        OA = np.diag(self.confusion_matrix).sum() / (self.confusion_matrix.sum() + self.eps)
        return OA

    def Intersection_over_Union(self):
        tp, fp, tn, fn = self.get_tp_fp_tn_fn()
        IoU = tp / (tp + fn + fp)
        return IoU

    def Dice(self):
        tp, fp, tn, fn = self.get_tp_fp_tn_fn()
        Dice = 2 * tp / ((tp + fp) + (tp + fn))
        return Dice

    def Pixel_Accuracy_Class(self):
        #         TP                                  TP+FP
        Acc = np.diag(self.confusion_matrix) / (self.confusion_matrix.sum(axis=0) + self.eps)
        return Acc

    def Frequency_Weighted_Intersection_over_Union(self):
        freq = np.sum(self.confusion_matrix, axis=1) / (np.sum(self.confusion_matrix) + self.eps)
        iou = self.Intersection_over_Union()
        FWIoU = (freq[freq > 0] * iou[freq > 0]).sum()
        return FWIoU

    def _generate_matrix(self, gt_image, pre_image):
        mask = (gt_image >= 0) & (gt_image < self.num_class)
        label = self.num_class * gt_image[mask].astype('int') + pre_image[mask]
        count = np.bincount(label, minlength=self.num_class ** 2)
        confusion_matrix = count.reshape(self.num_class, self.num_class)
        return confusion_matrix

    def add_batch(self, gt_image, pre_image):
        assert gt_image.shape == pre_image.shape, 'pre_image shape {}, gt_image shape {}'.format(pre_image.shape,
                                                                                                 gt_image.shape)
        self.confusion_matrix += self._generate_matrix(gt_image, pre_image)

    def reset(self):
        self.confusion_matrix = np.zeros((self.num_class,) * 2)

In [10]:
!pip install einops

  Obtaining dependency information for einops from https://files.pythonhosted.org/packages/29/0b/2d1c0ebfd092e25935b86509a9a817159212d82aa43d7fb07eca4eeff2c2/einops-0.7.0-py3-none-any.whl.metadata
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.6/44.6 kB 3.0 MB/s eta 0:00:00


# Model

In [11]:
# import torch

# # Instantiate your UNet model
# model = A2FPN()


# # Print the shape of the outputmodel = UNet(n_class=6)

# # Create a dummy batch with random images
# dummy_batch_size = 4  # Choose your batch size
# dummy_input_batch = torch.randn(dummy_batch_size, 3, 256, 256)  # Batch size, 3 channels, 256x256

# # Forward pass
# output_batch = model(dummy_input_batch)

# # Print the shape of the output batch

# print("Output batch shape:", output_batch.shape)

# Loss function

In [12]:
def label_smoothed_nll_loss(
    lprobs: torch.Tensor, target: torch.Tensor, epsilon: float, ignore_index=None, reduction="mean", dim=-1
) -> torch.Tensor:
    """

    Source: https://github.com/pytorch/fairseq/blob/master/fairseq/criterions/label_smoothed_cross_entropy.py

    :param lprobs: Log-probabilities of predictions (e.g after log_softmax)
    :param target:
    :param epsilon:
    :param ignore_index:
    :param reduction:
    :return:
    """
    if target.dim() == lprobs.dim() - 1:
        target = target.unsqueeze(dim)

    if ignore_index is not None:
        pad_mask = target.eq(ignore_index)
        target = target.masked_fill(pad_mask, 0)
        nll_loss = -lprobs.gather(dim=dim, index=target)
        smooth_loss = -lprobs.sum(dim=dim, keepdim=True)

        # nll_loss.masked_fill_(pad_mask, 0.0)
        # smooth_loss.masked_fill_(pad_mask, 0.0)
        nll_loss = nll_loss.masked_fill(pad_mask, 0.0)
        smooth_loss = smooth_loss.masked_fill(pad_mask, 0.0)
    else:
        nll_loss = -lprobs.gather(dim=dim, index=target)
        smooth_loss = -lprobs.sum(dim=dim, keepdim=True)

        nll_loss = nll_loss.squeeze(dim)
        smooth_loss = smooth_loss.squeeze(dim)

    if reduction == "sum":
        nll_loss = nll_loss.sum()
        smooth_loss = smooth_loss.sum()
    if reduction == "mean":
        nll_loss = nll_loss.mean()
        smooth_loss = smooth_loss.mean()

    eps_i = epsilon / lprobs.size(dim)
    loss = (1.0 - epsilon) * nll_loss + eps_i * smooth_loss
    return loss

In [13]:
__all__ = ["SoftCrossEntropyLoss"]
from typing import Optional
from torch.nn.modules.loss import _Loss
from typing import List
class SoftCrossEntropyLoss(nn.Module):
    """
    Drop-in replacement for nn.CrossEntropyLoss with few additions:
    - Support of label smoothing
    """

    __constants__ = ["reduction", "ignore_index", "smooth_factor"]

    def __init__(self, reduction: str = "mean", smooth_factor: float = 0.0, ignore_index: Optional[int] = -100, dim=1):
        super().__init__()
        self.smooth_factor = smooth_factor
        self.ignore_index = ignore_index
        self.reduction = reduction
        self.dim = dim

    def forward(self, input: Tensor, target: Tensor) -> Tensor:
        log_prob = F.log_softmax(input, dim=self.dim)
        pad_mask = target.eq(self.ignore_index)
        target = target.masked_fill(pad_mask, 0)
        log_prob = log_prob.masked_fill(pad_mask.unsqueeze(1), 0)
        return label_smoothed_nll_loss(
            log_prob,
            target,
            epsilon=self.smooth_factor,
            ignore_index=self.ignore_index,
            reduction=self.reduction,
            dim=self.dim,
        )
__all__ = ["JointLoss", "WeightedLoss"]


class WeightedLoss(_Loss):
    """Wrapper class around loss function that applies weighted with fixed factor.
    This class helps to balance multiple losses if they have different scales
    """

    def __init__(self, loss, weight=1.0):
        super().__init__()
        self.loss = loss
        self.weight = weight

    def forward(self, *input):
        return self.loss(*input) * self.weight
class JointLoss(_Loss):
    """
    Wrap two loss functions into one. This class computes a weighted sum of two losses.
    """

    def __init__(self, first: nn.Module, second: nn.Module, first_weight=1.0, second_weight=1.0):
        super().__init__()
        self.first = WeightedLoss(first, first_weight)
        self.second = WeightedLoss(second, second_weight)

    def forward(self, *input):
        return self.first(*input) + self.second(*input)
__all__ = ["DiceLoss"]

BINARY_MODE = "binary"
MULTICLASS_MODE = "multiclass"
MULTILABEL_MODE = "multilabel"
def soft_dice_score(
    output: torch.Tensor, target: torch.Tensor, smooth: float = 0.0, eps: float = 1e-7, dims=None
) -> torch.Tensor:
    """

    :param output:
    :param target:
    :param smooth:
    :param eps:
    :return:

    Shape:
        - Input: :math:`(N, NC, *)` where :math:`*` means any number
            of additional dimensions
        - Target: :math:`(N, NC, *)`, same shape as the input
        - Output: scalar.

    """
    assert output.size() == target.size()
    if dims is not None:
        intersection = torch.sum(output * target, dim=dims)
        cardinality = torch.sum(output + target, dim=dims)
    else:
        intersection = torch.sum(output * target)
        cardinality = torch.sum(output + target)
    dice_score = (2.0 * intersection + smooth) / (cardinality + smooth).clamp_min(eps)
    return dice_score
class DiceLoss(_Loss):
    """
    Implementation of Dice loss for image segmentation task.
    It supports binary, multiclass and multilabel cases
    """

    def __init__(
        self,
        mode: str = 'multiclass',
        classes: List[int] = None,
        log_loss=False,
        from_logits=True,
        smooth: float = 0.0,
        ignore_index=None,
        eps=1e-7,
    ):
        """

        :param mode: Metric mode {'binary', 'multiclass', 'multilabel'}
        :param classes: Optional list of classes that contribute in loss computation;
        By default, all channels are included.
        :param log_loss: If True, loss computed as `-log(jaccard)`; otherwise `1 - jaccard`
        :param from_logits: If True assumes input is raw logits
        :param smooth:
        :param ignore_index: Label that indicates ignored pixels (does not contribute to loss)
        :param eps: Small epsilon for numerical stability
        """
        assert mode in {BINARY_MODE, MULTILABEL_MODE, MULTICLASS_MODE}
        super(DiceLoss, self).__init__()
        self.mode = mode
        if classes is not None:
            assert mode != BINARY_MODE, "Masking classes is not supported with mode=binary"
            classes = to_tensor(classes, dtype=torch.long)

        self.classes = classes
        self.from_logits = from_logits
        self.smooth = smooth
        self.eps = eps
        self.ignore_index = ignore_index
        self.log_loss = log_loss

    def forward(self, y_pred: Tensor, y_true: Tensor) -> Tensor:
        """

        :param y_pred: NxCxHxW
        :param y_true: NxHxW
        :return: scalar
        """
        assert y_true.size(0) == y_pred.size(0)

        if self.from_logits:
            # Apply activations to get [0..1] class probabilities
            # Using Log-Exp as this gives more numerically stable result and does not cause vanishing gradient on
            # extreme values 0 and 1
            if self.mode == MULTICLASS_MODE:
                y_pred = y_pred.log_softmax(dim=1).exp()
            else:
                y_pred = F.logsigmoid(y_pred).exp()

        bs = y_true.size(0)
        num_classes = y_pred.size(1)
        dims = (0, 2)

        if self.mode == BINARY_MODE:
            y_true = y_true.view(bs, 1, -1)
            y_pred = y_pred.view(bs, 1, -1)

            if self.ignore_index is not None:
                mask = y_true != self.ignore_index
                y_pred = y_pred * mask
                y_true = y_true * mask

        if self.mode == MULTICLASS_MODE:
            y_true = y_true.view(bs, -1)
            y_pred = y_pred.view(bs, num_classes, -1)

            if self.ignore_index is not None:
                mask = y_true != self.ignore_index
                y_pred = y_pred * mask.unsqueeze(1)

                y_true = F.one_hot((y_true * mask).to(torch.long), num_classes)  # N,H*W -> N,H*W, C
                y_true = y_true.permute(0, 2, 1) * mask.unsqueeze(1)  # H, C, H*W
            else:
                y_true = F.one_hot(y_true, num_classes)  # N,H*W -> N,H*W, C
                y_true = y_true.permute(0, 2, 1)  # H, C, H*W

        if self.mode == MULTILABEL_MODE:
            y_true = y_true.view(bs, num_classes, -1)
            y_pred = y_pred.view(bs, num_classes, -1)

            if self.ignore_index is not None:
                mask = y_true != self.ignore_index
                y_pred = y_pred * mask
                y_true = y_true * mask

        scores = soft_dice_score(y_pred, y_true.type_as(y_pred), smooth=self.smooth, eps=self.eps, dims=dims)

        if self.log_loss:
            loss = -torch.log(scores.clamp_min(self.eps))
        else:
            loss = 1.0 - scores

        # Dice loss is undefined for non-empty classes
        # So we zero contribution of channel that does not have true pixels
        # NOTE: A better workaround would be to use loss term `mean(y_pred)`
        # for this case, however it will be a modified jaccard loss

        mask = y_true.sum(dims) > 0
        loss *= mask.to(loss.dtype)

        if self.classes is not None:
            loss = loss[self.classes]

        return loss.mean()


In [14]:

class UnetLoss(nn.Module):
    def __init__(self, ignore_index=255):
        super().__init__()
        self.main_loss = JointLoss(SoftCrossEntropyLoss(smooth_factor=0.05, ignore_index=ignore_index),
                                   DiceLoss(smooth=0.05, ignore_index=ignore_index), 1.0, 1.0)
        self.aux_loss = SoftCrossEntropyLoss(smooth_factor=0.05, ignore_index=ignore_index)

    def forward(self, logits, labels):
        if self.training and len(logits) == 2:
            logit_main, logit_aux = logits
            loss = self.main_loss(logit_main, labels) + 0.4 * self.aux_loss(logit_aux, labels)
        else:
            loss = self.main_loss(logits, labels)

        return loss

# Training

**Initialize weights**

In [15]:
def weights_init(model):
    if isinstance(model, nn.Linear):
        # Xavier Distribution
        torch.nn.init.xavier_uniform_(model.weight)

In [16]:
def save_model(model, optimizer, path):
    checkpoint = {
        "model": model.state_dict(),
        "optimizer": optimizer.state_dict(),
    }
    torch.save(checkpoint, path)

def load_model(model, optimizer, path):
    checkpoint = torch.load(path)
    model.load_state_dict(checkpoint["model"])
    optimizer.load_state_dict(checkpoint['optimizer'])
    return model, optimizer

**Train model**

In [17]:
def train(train_dataloader, valid_dataloader, learing_rate_scheduler, epoch, display_step):
    print(f"Start epoch #{epoch+1}, learning rate for this epoch: {learing_rate_scheduler.get_last_lr()}")
    start_time = time.time()
    train_loss_epoch = 0
    test_loss_epoch = 0
    last_loss = 999999999
    model.train()
    metrics_train = Evaluator(num_class=6)
    metrics_val = Evaluator(num_class=6)

    for i,input in enumerate(tqdm(train_dataloader)):
        # Load data into GPU
        data=input['img']
        masks_true = input['gt_semantic_seg']
        data,mask = data.to(device),masks_true.to(device)
        optimizer.zero_grad()
        prediction = model(data)
        # Backpropagation, compute gradients
        loss = loss_function(prediction, mask.long())
        pre_mask = nn.Softmax(dim=1)(prediction)
        pre_mask = pre_mask.argmax(dim=1)
        for i in range(mask.shape[0]):
            metrics_train.add_batch(mask[i].cpu().numpy(), pre_mask[i].cpu().numpy())
        loss.backward()

        # Apply gradients
        optimizer.step()

        # Save loss
        train_loss_epoch += loss.item()
    print(f"Done epoch #{epoch+1}, time for this epoch: {time.time()-start_time}s")
    train_loss_epoch /= (i + 1)
    mIoU = np.nanmean(metrics_train.Intersection_over_Union()[:-1])
    F1 = np.nanmean(metrics_train.F1()[:-1])
    OA = np.nanmean(metrics_train.OA())
    iou_per_class = metrics_train.Intersection_over_Union()
    train_eval_value =  (iou_per_class,mIoU,F1,OA)
    metrics_train.reset()
    # Evaluate the validation set
    model.eval()
    with torch.no_grad():
        for k,input in enumerate(tqdm(valid_dataloader)):
            data=input['img'].to(device)
            mask = input['gt_semantic_seg'].to(device)
            prediction = model(data)
            test_loss = loss_function(prediction, mask.long())
            pre_mask = nn.Softmax(dim=1)(prediction)
            pre_mask = pre_mask.argmax(dim=1)
            test_loss_epoch += test_loss.item()
            if k<=3:
            # Convert predictions to 2D array
                predictions_2d = pre_mask[0].cpu().numpy()  # Assuming you want the first prediction

            # Convert ground truth masks to 2D array
                masks_true_2d = mask[0].cpu().numpy()  # Assuming you want the first ground truth mask

            # Convert to np.int8 if needed
                predictions_2d = predictions_2d.astype(np.int8)
                masks_true_2d = masks_true_2d.astype(np.int8)
                wandb.log(
      {f"val_image{k}" : wandb.Image(data[0], masks={
        "predictions" : {
            "mask_data" : predictions_2d,
            "class_labels" : class_label
        },
        "ground_truth" : {
            "mask_data" : masks_true_2d,
            "class_labels" : class_label
        }
    })})
            for i in range(mask.shape[0]):
                metrics_val.add_batch(mask[i].cpu().numpy(), pre_mask[i].cpu().numpy())
    test_loss_epoch /= (i + 1)
    mIoU = np.nanmean(metrics_val.Intersection_over_Union()[:-1])
    F1 = np.nanmean(metrics_val.F1()[:-1])
    OA = np.nanmean(metrics_val.OA())
    iou_per_class_val = metrics_val.Intersection_over_Union()
    eval_value =  (iou_per_class_val,mIoU,F1,OA)
    print(eval_value)
    metrics_val.reset()
    return train_loss_epoch, train_eval_value, test_loss_epoch, eval_value


**Test model**

In [18]:
device

device(type='cuda')

In [19]:
!pip install segmentation-models-pytorch

  Obtaining dependency information for segmentation-models-pytorch from https://files.pythonhosted.org/packages/cb/70/4aac1b240b399b108ce58029ae54bc14497e1bbc275dfab8fd3c84c1e35d/segmentation_models_pytorch-0.3.3-py3-none-any.whl.metadata
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.8/58.8 kB 4.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... - \ done
  Preparing metadata (setup.py) ... - done
  Obtaining dependency information for timm==0.9.2 from https://files.pythonhosted.org/packages/29/90/94f5deb8d76e24a89813aef95e8809ca8fd7414490428480eda19b133d4a/timm-0.9.2-py3-none-any.whl.metadata
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.5/68.5 kB 6.6 MB/s eta 0:00:00
  Obtaining dependency information for munch from https://files.pythonhosted.org/packages/56/b3/7c69b37f03260a061883bec0e7b05be7117c1b1c85f5212c72c8c2bc3c8c/munch-4.0.0-py2.py3-none-any.whl.metadata
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.7/106.7 kB 11.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━

In [20]:
import segmentation_models_pytorch as smp

model = smp.UnetPlusPlus(
    encoder_name="resnet34",        
    encoder_weights="imagenet",     
    in_channels=3,                  
    classes=6     
)

model.to(device)

Downloading: "https://download.pytorch.org/models/resnet34-333f7ec4.pth" to /root/.cache/torch/hub/checkpoints/resnet34-333f7ec4.pth
100%|██████████| 83.3M/83.3M [00:00<00:00, 219MB/s]


UnetPlusPlus(
  (encoder): ResNetEncoder(
    (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU(inplace=True)
    (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    (layer1): Sequential(
      (0): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace=True)
        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (1): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=Tru

In [21]:
import torch

# Check if CUDA is available
if torch.cuda.is_available():
    # Use GPU-accelerated PyTorch functions here
    print("CUDA is available.")
else:
    print("CUDA is not available.")

CUDA is available.


In [22]:

loss_function = UnetLoss(ignore_index=6)
# Define the optimizer (Adam optimizer)
optimizer = optim.Adam(params=model.parameters(), lr=learning_rate)
# optimizer.load_state_dict(checkpoint['optimizer'])

# Learning rate scheduler
learing_rate_scheduler = lr_scheduler.StepLR(optimizer, step_size=4, gamma=0.6)

In [23]:
save_model(model, optimizer, checkpoint_path)
load_checkpoint_flag=False

In [24]:
# print("Model keys:")
# print(model.state_dict().keys())

# print("\nCheckpoint keys:")
# print(checkpoint['model'].keys())


In [25]:
# Load the model checkpoint if needed
# Load the model checkpoint if needed
if load_checkpoint_flag:
    model, optimize= load_model(model, optimizer, pretrained_path)
    


In [26]:
torch.cuda.empty_cache()

In [27]:

wandb.login(
    # set the wandb project where this run will be logged
#     project= "PolypSegment", 
    key = "b98d2b806f364f5af900550ec98e26e2f418e8a7",
)
wandb.init(
    project = "unetplusplus_tuning"
)



wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin
wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: trithuy2003 (deepbk). Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.16.1
wandb: Run data is saved locally in /kaggle/working/wandb/run-20231216_114033-ubeetgwe
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run helpful-eon-9
wandb: ⭐️ View project at https://wandb.ai/deepbk/unetplusplus_tuning
wandb: 🚀 View run at https://wandb.ai/deepbk/unetplusplus_tuning/runs/ubeetgwe


In [28]:

# Training loop
train_loss_array = []
test_loss_array = []
last_loss = 9999999999999
for epoch in range(40):
    try:
        train_loss_epoch = 0
        test_loss_epoch = 0
        train_loss_epoch, train_eval_value, test_loss_epoch, eval_value = train(train_loader, 
                                                  val_loader, 
                                                  learing_rate_scheduler, epoch, display_step)

        if test_loss_epoch < last_loss:
            save_model(model, optimizer, checkpoint_path)
            last_loss = test_loss_epoch

        iou_value = {}
        iou_per_class,mIoU,F1,OA=train_eval_value
        eval_value_train = {'mIoU': mIoU,
                          'F1': F1,
                          'OA': OA}                                          
        print('train:', eval_value_train)
        train_accuracy.append(OA)
        wandb.log({'mIoU_train': mIoU,
                          'F1_train': F1,
                          'OA_train': OA}) 

        for class_name, iou in zip(CLASSES,iou_per_class):
            wandb.log({f"{class_name}_train_IOU": iou})
            iou_value[class_name] = iou
        print(iou_value)

        iou_value = {}
        iou_per_class,mIoU,F1,OA = eval_value
        eval_value_val = {'mIoU': mIoU,
                          'F1': F1,
                          'OA': OA}                                          
        print('val:', eval_value_val)
        valid_accuracy.append(OA)
        wandb.log({'mIoU_val': mIoU,
                          'F1_val': F1,
                          'OA_val': OA})
        for class_name, iou in zip(CLASSES,iou_per_class):
            wandb.log({f"{class_name}_val_IoU": iou})
            iou_value[class_name] = iou
        print(iou_value)

        learing_rate_scheduler.step()
        train_loss_array.append(train_loss_epoch)
        test_loss_array.append(test_loss_epoch)
        wandb.log({"Train loss": train_loss_epoch, "Valid loss": test_loss_epoch})
        print("Epoch {}: loss: {:.4f}, train accuracy: {:.4f}, valid accuracy:{:.4f}".format(epoch + 1, 
                                            train_loss_array[-1], train_accuracy[-1], valid_accuracy[-1]))
    except:
        torch.cuda.empty_cache()


Start epoch #1, learning rate for this epoch: [0.001]


100%|██████████| 312/312 [04:05<00:00,  1.27it/s]


Done epoch #1, time for this epoch: 245.98548126220703s


100%|██████████| 88/88 [00:20<00:00,  4.20it/s]


(array([0.49148501, 0.39317315, 0.22669158, 0.29615695, 0.5553317 ,
       0.04467074]), 0.39256767777341944, 0.5528317637345344, 0.5238985169815314)
train: {'mIoU': 0.4532835015379728, 'F1': 0.6207107097769999, 'OA': 0.6372596331131763}
{'ImSurf': 0.4925088031720075, 'Building': 0.5095192321219401, 'LowVeg': 0.47614477805557953, 'Tree': 0.4649576011363042, 'Car': 0.32328709320403265, 'Clutter': 0.03316370096161863}
val: {'mIoU': 0.39256767777341944, 'F1': 0.5528317637345344, 'OA': 0.5238985169815314}
{'ImSurf': 0.49148501014474455, 'Building': 0.3931731522834272, 'LowVeg': 0.22669157805251644, 'Tree': 0.2961569473463578, 'Car': 0.555331701040051, 'Clutter': 0.044670744935739894}
Epoch 1: loss: 32.4185, train accuracy: 0.6373, valid accuracy:0.5239
Start epoch #2, learning rate for this epoch: [0.001]


100%|██████████| 312/312 [02:37<00:00,  1.98it/s]


Done epoch #2, time for this epoch: 157.2873854637146s


100%|██████████| 88/88 [00:13<00:00,  6.53it/s]


(array([0.5697355 , 0.58815152, 0.51622865, 0.41012205, 0.62291768,
       0.1830455 ]), 0.5414310781994266, 0.6993693398262716, 0.684102186434404)
train: {'mIoU': 0.5695009705619323, 'F1': 0.725314232111532, 'OA': 0.7053619928849049}
{'ImSurf': 0.5635724470399377, 'Building': 0.6138469146508824, 'LowVeg': 0.5439079319713466, 'Tree': 0.5395162608526268, 'Car': 0.5866612982948679, 'Clutter': 0.12268184763547786}
val: {'mIoU': 0.5414310781994266, 'F1': 0.6993693398262716, 'OA': 0.684102186434404}
{'ImSurf': 0.5697354982418809, 'Building': 0.5881515168796646, 'LowVeg': 0.516228651617797, 'Tree': 0.410122047626136, 'Car': 0.6229176766316545, 'Clutter': 0.18304549797101616}
Epoch 2: loss: 27.6150, train accuracy: 0.7054, valid accuracy:0.6841
Start epoch #3, learning rate for this epoch: [0.001]


100%|██████████| 312/312 [02:34<00:00,  2.01it/s]


Done epoch #3, time for this epoch: 154.9977161884308s


100%|██████████| 88/88 [00:13<00:00,  6.54it/s]


(array([0.62878611, 0.70707525, 0.59355653, 0.56433463, 0.59790254,
       0.19023967]), 0.6183310111323804, 0.7630606461265137, 0.7530926158765365)
train: {'mIoU': 0.5998024806672072, 'F1': 0.7492386335206922, 'OA': 0.7283915495261167}
{'ImSurf': 0.5900846656684505, 'Building': 0.6513248792340494, 'LowVeg': 0.5599041580776185, 'Tree': 0.5679587758886191, 'Car': 0.6297399244672983, 'Clutter': 0.18147540819507002}
val: {'mIoU': 0.6183310111323804, 'F1': 0.7630606461265137, 'OA': 0.7530926158765365}
{'ImSurf': 0.6287861052366549, 'Building': 0.7070752503388352, 'LowVeg': 0.5935565284588722, 'Tree': 0.564334634728173, 'Car': 0.5979025368993667, 'Clutter': 0.19023966816507304}
Epoch 3: loss: 26.0036, train accuracy: 0.7284, valid accuracy:0.7531
Start epoch #4, learning rate for this epoch: [0.001]


100%|██████████| 312/312 [02:31<00:00,  2.05it/s]


Done epoch #4, time for this epoch: 151.93644738197327s


100%|██████████| 88/88 [00:13<00:00,  6.48it/s]


(array([0.63982642, 0.69662509, 0.54565317, 0.56939215, 0.61949151,
       0.22955851]), 0.6141976683526021, 0.7596524562753995, 0.7452782865744738)
train: {'mIoU': 0.6252773554060941, 'F1': 0.7686255699543448, 'OA': 0.748531848956377}
{'ImSurf': 0.6211583329922186, 'Building': 0.6888596599177002, 'LowVeg': 0.5742252129894326, 'Tree': 0.588676919737401, 'Car': 0.6534666513937182, 'Clutter': 0.20859103807347282}
val: {'mIoU': 0.6141976683526021, 'F1': 0.7596524562753995, 'OA': 0.7452782865744738}
{'ImSurf': 0.6398264182737963, 'Building': 0.696625087894814, 'LowVeg': 0.5456531721916023, 'Tree': 0.5693921489739654, 'Car': 0.6194915144288324, 'Clutter': 0.22955850830320784}
Epoch 4: loss: 24.6364, train accuracy: 0.7485, valid accuracy:0.7453
Start epoch #5, learning rate for this epoch: [0.0006]


100%|██████████| 312/312 [02:30<00:00,  2.08it/s]


Done epoch #5, time for this epoch: 150.35812330245972s


100%|██████████| 88/88 [00:12<00:00,  6.83it/s]


(array([0.66163007, 0.75982304, 0.63100817, 0.62871867, 0.7131503 ,
       0.28682561]), 0.6788660482538493, 0.8076500552541077, 0.7856555508779948)
train: {'mIoU': 0.6491442150171594, 'F1': 0.7862815204826796, 'OA': 0.7678029170403113}
{'ImSurf': 0.6400406785633075, 'Building': 0.7257112298997074, 'LowVeg': 0.5969122645211444, 'Tree': 0.608320205972186, 'Car': 0.6747366961294513, 'Clutter': 0.24681267269210105}
val: {'mIoU': 0.6788660482538493, 'F1': 0.8076500552541077, 'OA': 0.7856555508779948}
{'ImSurf': 0.6616300673974217, 'Building': 0.7598230353235026, 'LowVeg': 0.6310081678960419, 'Tree': 0.6287186729351133, 'Car': 0.7131502977171672, 'Clutter': 0.2868256115457465}
Epoch 5: loss: 23.2898, train accuracy: 0.7678, valid accuracy:0.7857
Start epoch #6, learning rate for this epoch: [0.0006]


100%|██████████| 312/312 [02:27<00:00,  2.11it/s]


Done epoch #6, time for this epoch: 147.56595730781555s


100%|██████████| 88/88 [00:12<00:00,  7.18it/s]


(array([0.66104669, 0.76141717, 0.65210152, 0.64754595, 0.6549637 ,
       0.27948944]), 0.675415006551952, 0.8054997595449741, 0.7946489475137966)
train: {'mIoU': 0.6709861141895115, 'F1': 0.8018858383999492, 'OA': 0.7842365442178189}
{'ImSurf': 0.6589070470009943, 'Building': 0.7597685992089239, 'LowVeg': 0.6096560934560723, 'Tree': 0.6279841892986925, 'Car': 0.6986146419828739, 'Clutter': 0.2688760467197292}
val: {'mIoU': 0.675415006551952, 'F1': 0.8054997595449741, 'OA': 0.7946489475137966}
{'ImSurf': 0.6610466864131641, 'Building': 0.7614171733534367, 'LowVeg': 0.6521015237006849, 'Tree': 0.6475459483316293, 'Car': 0.6549637009608449, 'Clutter': 0.27948943991996256}
Epoch 6: loss: 22.2682, train accuracy: 0.7842, valid accuracy:0.7946
Start epoch #7, learning rate for this epoch: [0.0006]


100%|██████████| 312/312 [02:26<00:00,  2.13it/s]


Done epoch #7, time for this epoch: 146.22972059249878s


100%|██████████| 88/88 [00:12<00:00,  7.07it/s]


(array([0.66410118, 0.77405513, 0.61840101, 0.55324045, 0.68440387,
       0.30040872]), 0.6588403275470279, 0.7920014641111587, 0.7797805665639861)
train: {'mIoU': 0.6776258566737998, 'F1': 0.8064968000614765, 'OA': 0.7904229072424082}
{'ImSurf': 0.6691015980515178, 'Building': 0.7763421905522322, 'LowVeg': 0.6117344910626809, 'Tree': 0.6362116878709003, 'Car': 0.694739315831668, 'Clutter': 0.2797059141308714}
val: {'mIoU': 0.6588403275470279, 'F1': 0.7920014641111587, 'OA': 0.7797805665639861}
{'ImSurf': 0.6641011799273487, 'Building': 0.7740551289241119, 'LowVeg': 0.6184010132979293, 'Tree': 0.553240447680913, 'Car': 0.6844038679048363, 'Clutter': 0.3004087183570836}
Epoch 7: loss: 21.7863, train accuracy: 0.7904, valid accuracy:0.7798
Start epoch #8, learning rate for this epoch: [0.0006]


100%|██████████| 312/312 [02:27<00:00,  2.12it/s]


Done epoch #8, time for this epoch: 147.09640336036682s


100%|██████████| 88/88 [00:12<00:00,  7.24it/s]


(array([0.67894271, 0.78648003, 0.65435335, 0.64218089, 0.68992647,
       0.30037939]), 0.6903766890597518, 0.8157893084753752, 0.8036734861002837)
train: {'mIoU': 0.687990856685629, 'F1': 0.8139664906348101, 'OA': 0.799206480001792}
{'ImSurf': 0.6804282151132726, 'Building': 0.7854894068232656, 'LowVeg': 0.6301589020674784, 'Tree': 0.6466505563133417, 'Car': 0.6972272031107869, 'Clutter': 0.289278730095502}
val: {'mIoU': 0.6903766890597518, 'F1': 0.8157893084753752, 'OA': 0.8036734861002837}
{'ImSurf': 0.6789427072359699, 'Building': 0.7864800310277957, 'LowVeg': 0.6543533469323096, 'Tree': 0.6421808862317612, 'Car': 0.6899264738709223, 'Clutter': 0.30037939496426896}
Epoch 8: loss: 21.2492, train accuracy: 0.7992, valid accuracy:0.8037
Start epoch #9, learning rate for this epoch: [0.00035999999999999997]


100%|██████████| 312/312 [02:29<00:00,  2.09it/s]


Done epoch #9, time for this epoch: 149.25019001960754s


100%|██████████| 88/88 [00:12<00:00,  7.21it/s]


(array([0.69196384, 0.78557859, 0.65704864, 0.64321065, 0.70681367,
       0.3411858 ]), 0.6969230769380429, 0.8203975748985926, 0.8070837542553727)
train: {'mIoU': 0.6998909123401265, 'F1': 0.8221989299241848, 'OA': 0.8093099685815665}
{'ImSurf': 0.6922735327349597, 'Building': 0.8040873907579437, 'LowVeg': 0.6428088430524221, 'Tree': 0.6585882372280983, 'Car': 0.701696557927208, 'Clutter': 0.3191106762668621}
val: {'mIoU': 0.6969230769380429, 'F1': 0.8203975748985926, 'OA': 0.8070837542553727}
{'ImSurf': 0.6919638355884884, 'Building': 0.7855785888617752, 'LowVeg': 0.6570486401874206, 'Tree': 0.64321064688112, 'Car': 0.7068136731714103, 'Clutter': 0.3411858027989064}
Epoch 9: loss: 20.5142, train accuracy: 0.8093, valid accuracy:0.8071
Start epoch #10, learning rate for this epoch: [0.00035999999999999997]


100%|██████████| 312/312 [02:25<00:00,  2.14it/s]


Done epoch #10, time for this epoch: 145.51325583457947s


100%|██████████| 88/88 [00:12<00:00,  7.19it/s]


(array([0.69570107, 0.78972706, 0.66275656, 0.64821025, 0.72731671,
       0.36350424]), 0.704742327806695, 0.8257866836277625, 0.8110590467158615)
train: {'mIoU': 0.71019762363591, 'F1': 0.829404350905633, 'OA': 0.8172219838851538}
{'ImSurf': 0.6975754892338748, 'Building': 0.8103380956972431, 'LowVeg': 0.6546741412003106, 'Tree': 0.6730469219466413, 'Car': 0.71535347010148, 'Clutter': 0.34729347563488566}
val: {'mIoU': 0.704742327806695, 'F1': 0.8257866836277625, 'OA': 0.8110590467158615}
{'ImSurf': 0.6957010666519877, 'Building': 0.7897270614898142, 'LowVeg': 0.6627565581387772, 'Tree': 0.648210246700011, 'Car': 0.7273167060528851, 'Clutter': 0.3635042419259991}
Epoch 10: loss: 19.9222, train accuracy: 0.8172, valid accuracy:0.8111
Start epoch #11, learning rate for this epoch: [0.00035999999999999997]


100%|██████████| 312/312 [02:22<00:00,  2.18it/s]


Done epoch #11, time for this epoch: 142.95338439941406s


100%|██████████| 88/88 [00:12<00:00,  7.07it/s]


(array([0.72188572, 0.81805266, 0.67688501, 0.67486097, 0.7130102 ,
       0.37335065]), 0.7209389114308824, 0.8368105238399849, 0.8255070825317995)
train: {'mIoU': 0.7227507668279171, 'F1': 0.8379828147824646, 'OA': 0.8249520980394803}
{'ImSurf': 0.7153145078207781, 'Building': 0.8200059107094332, 'LowVeg': 0.6682120829885568, 'Tree': 0.6816459892374868, 'Car': 0.7285753433833303, 'Clutter': 0.35025727626642444}
val: {'mIoU': 0.7209389114308824, 'F1': 0.8368105238399849, 'OA': 0.8255070825317995}
{'ImSurf': 0.7218857182936756, 'Building': 0.8180526573239801, 'LowVeg': 0.6768850091560205, 'Tree': 0.6748609749469752, 'Car': 0.7130101974337607, 'Clutter': 0.373350653141356}
Epoch 11: loss: 19.4415, train accuracy: 0.8250, valid accuracy:0.8255
Start epoch #12, learning rate for this epoch: [0.00035999999999999997]


100%|██████████| 312/312 [02:24<00:00,  2.16it/s]


Done epoch #12, time for this epoch: 144.60337114334106s


100%|██████████| 88/88 [00:12<00:00,  7.27it/s]


(array([0.70777492, 0.80619306, 0.67687987, 0.68099915, 0.71275033,
       0.30540646]), 0.716919465402427, 0.834282348706877, 0.821908122416631)
train: {'mIoU': 0.7275778886127211, 'F1': 0.8410699529562942, 'OA': 0.8287545962211413}
{'ImSurf': 0.7230385104350758, 'Building': 0.8308243584673014, 'LowVeg': 0.6644816953779402, 'Tree': 0.686376609789768, 'Car': 0.7331682689935195, 'Clutter': 0.3579062060408415}
val: {'mIoU': 0.716919465402427, 'F1': 0.834282348706877, 'OA': 0.821908122416631}
{'ImSurf': 0.7077749157038408, 'Building': 0.8061930606419514, 'LowVeg': 0.6768798718796861, 'Tree': 0.6809991516168322, 'Car': 0.7127503271698241, 'Clutter': 0.30540645904778635}
Epoch 12: loss: 19.1238, train accuracy: 0.8288, valid accuracy:0.8219
Start epoch #13, learning rate for this epoch: [0.00021599999999999996]


100%|██████████| 312/312 [02:25<00:00,  2.15it/s]


Done epoch #13, time for this epoch: 145.34250235557556s


100%|██████████| 88/88 [00:11<00:00,  7.45it/s]


(array([0.70867138, 0.81488035, 0.67536875, 0.67981687, 0.72385758,
       0.36876097]), 0.7205189852926389, 0.8365874439323541, 0.8251586278736034)
train: {'mIoU': 0.7320731077418701, 'F1': 0.8440522240535403, 'OA': 0.8334869421445407}
{'ImSurf': 0.7279420904457599, 'Building': 0.8386477993834766, 'LowVeg': 0.6719943690079871, 'Tree': 0.688600094633415, 'Car': 0.7331811852387119, 'Clutter': 0.38719201749550214}
val: {'mIoU': 0.7205189852926389, 'F1': 0.8365874439323541, 'OA': 0.8251586278736034}
{'ImSurf': 0.7086713774515738, 'Building': 0.8148803529234678, 'LowVeg': 0.6753687493474795, 'Tree': 0.6798168676774755, 'Car': 0.7238575790631981, 'Clutter': 0.36876097282612447}
Epoch 13: loss: 18.7568, train accuracy: 0.8335, valid accuracy:0.8252
Start epoch #14, learning rate for this epoch: [0.00021599999999999996]


100%|██████████| 312/312 [02:23<00:00,  2.17it/s]


Done epoch #14, time for this epoch: 143.74289083480835s


100%|██████████| 88/88 [00:12<00:00,  7.26it/s]


(array([0.72357888, 0.83942986, 0.68646636, 0.67293894, 0.74247783,
       0.39001377]), 0.732978374216038, 0.8446254098663376, 0.832339284750342)
train: {'mIoU': 0.743607651130753, 'F1': 0.8517825989701304, 'OA': 0.8402083042340401}
{'ImSurf': 0.7383851735695764, 'Building': 0.8449944686449643, 'LowVeg': 0.6841590697400299, 'Tree': 0.6989537628611738, 'Car': 0.7515457808380199, 'Clutter': 0.3965619696623727}
val: {'mIoU': 0.732978374216038, 'F1': 0.8446254098663376, 'OA': 0.832339284750342}
{'ImSurf': 0.7235788828612871, 'Building': 0.8394298609117367, 'LowVeg': 0.6864663621659254, 'Tree': 0.672938935491571, 'Car': 0.7424778296496694, 'Clutter': 0.3900137688162062}
Epoch 14: loss: 18.2564, train accuracy: 0.8402, valid accuracy:0.8323
Start epoch #15, learning rate for this epoch: [0.00021599999999999996]


100%|██████████| 312/312 [02:23<00:00,  2.18it/s]


Done epoch #15, time for this epoch: 143.4240550994873s


100%|██████████| 88/88 [00:12<00:00,  7.33it/s]


(array([0.71965225, 0.82144944, 0.68588521, 0.69190948, 0.74139342,
       0.39378495]), 0.732057958745856, 0.8444050497035794, 0.8316958195343345)
train: {'mIoU': 0.7458697723777983, 'F1': 0.8529911435293798, 'OA': 0.8427750636369754}
{'ImSurf': 0.7442591838084346, 'Building': 0.860314045752262, 'LowVeg': 0.6782011375876793, 'Tree': 0.6995390016309331, 'Car': 0.7470354931096828, 'Clutter': 0.41346342657064017}
val: {'mIoU': 0.732057958745856, 'F1': 0.8444050497035794, 'OA': 0.8316958195343345}
{'ImSurf': 0.7196522470780271, 'Building': 0.8214494373583028, 'LowVeg': 0.6858852050038642, 'Tree': 0.6919094805135058, 'Car': 0.7413934237755806, 'Clutter': 0.3937849531420684}
Epoch 15: loss: 18.1001, train accuracy: 0.8428, valid accuracy:0.8317
Start epoch #16, learning rate for this epoch: [0.00021599999999999996]


100%|██████████| 312/312 [02:23<00:00,  2.17it/s]


Done epoch #16, time for this epoch: 143.88951539993286s


  0%|          | 0/88 [00:00<?, ?it/s]Exception in thread Thread-24 (_pin_memory_loop):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 51, in _pin_memory_loop
    do_one_step()
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 28, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/opt/conda/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/opt/conda/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 307, in rebuild_storage_fd
    fd = df.detach()
  File "/opt/conda/lib/python3.10/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.r

Start epoch #17, learning rate for this epoch: [0.00021599999999999996]


100%|██████████| 312/312 [02:22<00:00,  2.19it/s]


Done epoch #17, time for this epoch: 142.66866254806519s


100%|██████████| 88/88 [00:11<00:00,  7.58it/s]


(array([0.73196445, 0.84086652, 0.69701635, 0.69910686, 0.74280713,
       0.39924847]), 0.742352261910202, 0.8511190128297231, 0.8407025142102812)
train: {'mIoU': 0.7488389525700956, 'F1': 0.8551550083360075, 'OA': 0.8444191156289517}
{'ImSurf': 0.7422616440898954, 'Building': 0.8551450207584296, 'LowVeg': 0.6887453867710601, 'Tree': 0.7049002429344426, 'Car': 0.7531424682966503, 'Clutter': 0.4196658765763408}
val: {'mIoU': 0.742352261910202, 'F1': 0.8511190128297231, 'OA': 0.8407025142102812}
{'ImSurf': 0.7319644497881747, 'Building': 0.8408665200679519, 'LowVeg': 0.6970163543381792, 'Tree': 0.6991068573348189, 'Car': 0.7428071280218844, 'Clutter': 0.3992484706124536}
Epoch 17: loss: 17.9054, train accuracy: 0.8444, valid accuracy:0.8407
Start epoch #18, learning rate for this epoch: [0.00012959999999999998]


100%|██████████| 312/312 [02:25<00:00,  2.14it/s]


Done epoch #18, time for this epoch: 145.7529718875885s


100%|██████████| 88/88 [00:12<00:00,  7.29it/s]


(array([0.73543226, 0.83755143, 0.68714832, 0.68577281, 0.7354291 ,
       0.41263367]), 0.7362667833816513, 0.8469720017694963, 0.8363998314500795)
train: {'mIoU': 0.756467627260798, 'F1': 0.8600651775442725, 'OA': 0.8526855554336157}
{'ImSurf': 0.7586951790454848, 'Building': 0.8679433678393441, 'LowVeg': 0.6965622397892048, 'Tree': 0.7134337416118659, 'Car': 0.7457036080180908, 'Clutter': 0.4407102656557636}
val: {'mIoU': 0.7362667833816513, 'F1': 0.8469720017694963, 'OA': 0.8363998314500795}
{'ImSurf': 0.7354322551563184, 'Building': 0.8375514311505661, 'LowVeg': 0.6871483242280177, 'Tree': 0.6857728086425883, 'Car': 0.7354290977307657, 'Clutter': 0.41263367403603496}
Epoch 18: loss: 17.4237, train accuracy: 0.8527, valid accuracy:0.8364
Start epoch #19, learning rate for this epoch: [0.00012959999999999998]


100%|██████████| 312/312 [02:25<00:00,  2.14it/s]


Done epoch #19, time for this epoch: 145.88532638549805s


100%|██████████| 88/88 [00:12<00:00,  7.22it/s]


(array([0.73851255, 0.8527195 , 0.69872678, 0.70263253, 0.7359299 ,
       0.44572488]), 0.7457042513294695, 0.8531945683413655, 0.8440433784260307)
train: {'mIoU': 0.7610688677693443, 'F1': 0.8630828318701017, 'OA': 0.8549642990796994}
{'ImSurf': 0.7593042067681237, 'Building': 0.869238032078634, 'LowVeg': 0.7031002972958962, 'Tree': 0.7120284394361825, 'Car': 0.7616733632678848, 'Clutter': 0.4508805111872041}
val: {'mIoU': 0.7457042513294695, 'F1': 0.8531945683413655, 'OA': 0.8440433784260307}
{'ImSurf': 0.7385125489995618, 'Building': 0.852719496703637, 'LowVeg': 0.6987267786948296, 'Tree': 0.7026325329616188, 'Car': 0.7359298992877001, 'Clutter': 0.4457248783394439}
Epoch 19: loss: 17.1715, train accuracy: 0.8550, valid accuracy:0.8440
Start epoch #20, learning rate for this epoch: [0.00012959999999999998]


100%|██████████| 312/312 [02:24<00:00,  2.15it/s]


Done epoch #20, time for this epoch: 144.8816409111023s


100%|██████████| 88/88 [00:11<00:00,  7.36it/s]


(array([0.71187126, 0.81636755, 0.6694267 , 0.69404847, 0.74233905,
       0.41739907]), 0.7268106056995369, 0.8408174159940242, 0.8265757345074983)
train: {'mIoU': 0.7649928993928112, 'F1': 0.8655768760381779, 'OA': 0.8579800373468643}
{'ImSurf': 0.7674072442808364, 'Building': 0.8738813434030677, 'LowVeg': 0.7032423449155022, 'Tree': 0.7168121164543567, 'Car': 0.7636214479102927, 'Clutter': 0.47522686935303193}
val: {'mIoU': 0.7268106056995369, 'F1': 0.8408174159940242, 'OA': 0.8265757345074983}
{'ImSurf': 0.7118712590248204, 'Building': 0.8163675505740842, 'LowVeg': 0.6694267018352933, 'Tree': 0.6940484654385962, 'Car': 0.7423390516248907, 'Clutter': 0.41739906527225057}
Epoch 20: loss: 16.9344, train accuracy: 0.8580, valid accuracy:0.8266
Start epoch #21, learning rate for this epoch: [0.00012959999999999998]


100%|██████████| 312/312 [02:25<00:00,  2.15it/s]


Done epoch #21, time for this epoch: 145.05205488204956s


100%|██████████| 88/88 [00:11<00:00,  7.75it/s]


(array([0.74146687, 0.85045579, 0.70783082, 0.68624603, 0.73031168,
       0.40360463]), 0.7432622371824522, 0.8515448490710817, 0.843232285608427)
train: {'mIoU': 0.7640861973343294, 'F1': 0.8650520254025528, 'OA': 0.8578353478358343}
{'ImSurf': 0.7683241711708583, 'Building': 0.8710682245256253, 'LowVeg': 0.7057870484031693, 'Tree': 0.7163094566059249, 'Car': 0.758942085966069, 'Clutter': 0.4625339290273055}
val: {'mIoU': 0.7432622371824522, 'F1': 0.8515448490710817, 'OA': 0.843232285608427}
{'ImSurf': 0.7414668689742955, 'Building': 0.8504557859252478, 'LowVeg': 0.7078308214814567, 'Tree': 0.6862460269826816, 'Car': 0.7303116825485799, 'Clutter': 0.40360463109809847}
Epoch 21: loss: 17.0140, train accuracy: 0.8578, valid accuracy:0.8432
Start epoch #22, learning rate for this epoch: [7.775999999999999e-05]


100%|██████████| 312/312 [02:22<00:00,  2.19it/s]


Done epoch #22, time for this epoch: 142.32923436164856s


100%|██████████| 88/88 [00:13<00:00,  6.77it/s]


(array([0.74002451, 0.84453196, 0.69750021, 0.70189195, 0.74584073,
       0.42943987]), 0.7459578684906509, 0.8534718575982229, 0.8436430022601847)
train: {'mIoU': 0.7738578855551167, 'F1': 0.8713010721012043, 'OA': 0.8648877357825254}
{'ImSurf': 0.7785814861670434, 'Building': 0.8833215069205594, 'LowVeg': 0.7188290106337667, 'Tree': 0.7258840123009648, 'Car': 0.7626734117532491, 'Clutter': 0.48153539601644246}
val: {'mIoU': 0.7459578684906509, 'F1': 0.8534718575982229, 'OA': 0.8436430022601847}
{'ImSurf': 0.7400245070282402, 'Building': 0.8445319550667008, 'LowVeg': 0.6975002067433814, 'Tree': 0.7018919481648441, 'Car': 0.7458407254500884, 'Clutter': 0.42943986810751117}
Epoch 22: loss: 16.5226, train accuracy: 0.8649, valid accuracy:0.8436
Start epoch #23, learning rate for this epoch: [7.775999999999999e-05]


100%|██████████| 312/312 [02:23<00:00,  2.17it/s]


Done epoch #23, time for this epoch: 143.47148275375366s


100%|██████████| 88/88 [00:11<00:00,  7.87it/s]


(array([0.74500483, 0.84005155, 0.7014557 , 0.69641948, 0.74495167,
       0.44006706]), 0.7455766475244159, 0.8532728041186791, 0.8439818722518843)
train: {'mIoU': 0.7733774029402392, 'F1': 0.8710178791416057, 'OA': 0.8636940381465814}
{'ImSurf': 0.7724433751803105, 'Building': 0.8816785331750066, 'LowVeg': 0.7163224941213576, 'Tree': 0.7274851886502351, 'Car': 0.7689574235742858, 'Clutter': 0.4760155512592716}
val: {'mIoU': 0.7455766475244159, 'F1': 0.8532728041186791, 'OA': 0.8439818722518843}
{'ImSurf': 0.7450048307613945, 'Building': 0.8400515535218354, 'LowVeg': 0.7014557010688004, 'Tree': 0.6964194846173983, 'Car': 0.7449516676526504, 'Clutter': 0.44006705564861587}
Epoch 23: loss: 16.5893, train accuracy: 0.8637, valid accuracy:0.8440
Start epoch #24, learning rate for this epoch: [7.775999999999999e-05]


100%|██████████| 312/312 [02:21<00:00,  2.20it/s]


Done epoch #24, time for this epoch: 141.6481077671051s


100%|██████████| 88/88 [00:11<00:00,  7.91it/s]


(array([0.74002931, 0.84983844, 0.70456727, 0.69528592, 0.75005874,
       0.41782648]), 0.7479559384444522, 0.8547078966904931, 0.8452793841557115)
train: {'mIoU': 0.7712420741386954, 'F1': 0.8696316771449878, 'OA': 0.864136992356716}
{'ImSurf': 0.7733142360024289, 'Building': 0.8817475108408194, 'LowVeg': 0.7150994198565541, 'Tree': 0.7270221685505155, 'Car': 0.7590270354431587, 'Clutter': 0.5010682188584197}
val: {'mIoU': 0.7479559384444522, 'F1': 0.8547078966904931, 'OA': 0.8452793841557115}
{'ImSurf': 0.7400293134626446, 'Building': 0.8498384420612468, 'LowVeg': 0.7045672734172239, 'Tree': 0.6952859224736434, 'Car': 0.750058740807502, 'Clutter': 0.41782647956482516}
Epoch 24: loss: 16.5111, train accuracy: 0.8641, valid accuracy:0.8453
Start epoch #25, learning rate for this epoch: [7.775999999999999e-05]


100%|██████████| 312/312 [02:21<00:00,  2.21it/s]


Done epoch #25, time for this epoch: 141.19016814231873s


100%|██████████| 88/88 [00:11<00:00,  7.47it/s]


(array([0.74216572, 0.83667352, 0.70132196, 0.70810697, 0.72969376,
       0.40279458]), 0.743592387620453, 0.8520722171434203, 0.8439323825110484)
train: {'mIoU': 0.775144102912354, 'F1': 0.8722046451077634, 'OA': 0.8658422231674194}
{'ImSurf': 0.7808384874204043, 'Building': 0.8809680303292053, 'LowVeg': 0.7209319660085485, 'Tree': 0.7318776255828019, 'Car': 0.7611044052208101, 'Clutter': 0.4767230915921516}
val: {'mIoU': 0.743592387620453, 'F1': 0.8520722171434203, 'OA': 0.8439323825110484}
{'ImSurf': 0.7421657199621318, 'Building': 0.8366735224068892, 'LowVeg': 0.7013219642260584, 'Tree': 0.7081069682198883, 'Car': 0.7296937632872977, 'Clutter': 0.40279458318988315}
Epoch 25: loss: 16.3996, train accuracy: 0.8658, valid accuracy:0.8439
Start epoch #26, learning rate for this epoch: [4.665599999999999e-05]


100%|██████████| 312/312 [02:22<00:00,  2.19it/s]


Done epoch #26, time for this epoch: 142.71455574035645s


100%|██████████| 88/88 [00:11<00:00,  7.48it/s]


(array([0.72338394, 0.83212975, 0.69512177, 0.69552487, 0.73483032,
       0.40262851]), 0.7361981298767196, 0.8471168542140921, 0.8365866283846688)
train: {'mIoU': 0.7765393699991205, 'F1': 0.8729638521721726, 'OA': 0.8683661130758432}
{'ImSurf': 0.783183619674281, 'Building': 0.8883671849206968, 'LowVeg': 0.7184732045612607, 'Tree': 0.7325867090012279, 'Car': 0.7600861318381361, 'Clutter': 0.5083147961244512}
val: {'mIoU': 0.7361981298767196, 'F1': 0.8471168542140921, 'OA': 0.8365866283846688}
{'ImSurf': 0.7233839403821006, 'Building': 0.8321297497321292, 'LowVeg': 0.6951217732874744, 'Tree': 0.6955248688211673, 'Car': 0.7348303171607269, 'Clutter': 0.4026285142929279}
Epoch 26: loss: 16.2443, train accuracy: 0.8684, valid accuracy:0.8366
Start epoch #27, learning rate for this epoch: [4.665599999999999e-05]


100%|██████████| 312/312 [02:22<00:00,  2.19it/s]


Done epoch #27, time for this epoch: 142.58886456489563s


100%|██████████| 88/88 [00:11<00:00,  7.73it/s]


(array([0.74925665, 0.85235983, 0.71878348, 0.70779009, 0.75054548,
       0.43990166]), 0.7557471023617236, 0.8599469048731313, 0.8514627756528175)
train: {'mIoU': 0.779067651215287, 'F1': 0.8746526031245025, 'OA': 0.869708348543216}
{'ImSurf': 0.7869745170394059, 'Building': 0.8857575260467193, 'LowVeg': 0.7259732583010589, 'Tree': 0.7295618935598076, 'Car': 0.7670710611294429, 'Clutter': 0.5162990138367415}
val: {'mIoU': 0.7557471023617236, 'F1': 0.8599469048731313, 'OA': 0.8514627756528175}
{'ImSurf': 0.749256648336691, 'Building': 0.8523598265085983, 'LowVeg': 0.7187834750850834, 'Tree': 0.7077900864361631, 'Car': 0.750545475442082, 'Clutter': 0.4399016632583173}
Epoch 27: loss: 16.0784, train accuracy: 0.8697, valid accuracy:0.8515
Start epoch #28, learning rate for this epoch: [4.665599999999999e-05]


100%|██████████| 312/312 [02:23<00:00,  2.18it/s]


Done epoch #28, time for this epoch: 143.41901063919067s


100%|██████████| 88/88 [00:11<00:00,  7.46it/s]


(array([0.73906514, 0.83797814, 0.70598012, 0.70852175, 0.74463817,
       0.44032419]), 0.7472366635458979, 0.8544971773772753, 0.8453168793710459)
train: {'mIoU': 0.7799890731767847, 'F1': 0.8752035365882694, 'OA': 0.8693404044860449}
{'ImSurf': 0.7885067700436802, 'Building': 0.8872879720194504, 'LowVeg': 0.7241432762488923, 'Tree': 0.7298413241244848, 'Car': 0.7701660234474156, 'Clutter': 0.5064828990448674}
val: {'mIoU': 0.7472366635458979, 'F1': 0.8544971773772753, 'OA': 0.8453168793710459}
{'ImSurf': 0.7390651352096966, 'Building': 0.8379781424640185, 'LowVeg': 0.7059801216146018, 'Tree': 0.7085217465859929, 'Car': 0.7446381718551797, 'Clutter': 0.440324190187041}
Epoch 28: loss: 16.0322, train accuracy: 0.8693, valid accuracy:0.8453
Start epoch #29, learning rate for this epoch: [4.665599999999999e-05]


100%|██████████| 312/312 [02:21<00:00,  2.20it/s]


Done epoch #29, time for this epoch: 141.87280988693237s


100%|██████████| 88/88 [00:11<00:00,  7.45it/s]


(array([0.74663192, 0.85171179, 0.70599873, 0.70399501, 0.74524823,
       0.42750448]), 0.7507171347497722, 0.8565684794962338, 0.8468222854296593)
train: {'mIoU': 0.7810014387416819, 'F1': 0.875791580197847, 'OA': 0.8707854533806826}
{'ImSurf': 0.7859429279182039, 'Building': 0.8930629195562345, 'LowVeg': 0.7256775804088796, 'Tree': 0.7326573131782061, 'Car': 0.7676664526468855, 'Clutter': 0.5029702606990061}
val: {'mIoU': 0.7507171347497722, 'F1': 0.8565684794962338, 'OA': 0.8468222854296593}
{'ImSurf': 0.746631923334294, 'Building': 0.8517117893184037, 'LowVeg': 0.7059987277961588, 'Tree': 0.7039950052172336, 'Car': 0.745248228082771, 'Clutter': 0.4275044832747638}
Epoch 29: loss: 16.0453, train accuracy: 0.8708, valid accuracy:0.8468
Start epoch #30, learning rate for this epoch: [2.7993599999999992e-05]


100%|██████████| 312/312 [02:21<00:00,  2.20it/s]


Done epoch #30, time for this epoch: 141.82536435127258s


100%|██████████| 88/88 [00:11<00:00,  7.70it/s]


(array([0.74364947, 0.8437467 , 0.71159837, 0.71219826, 0.74223052,
       0.43445892]), 0.7506846637805612, 0.8567383187146783, 0.8479919104976612)
train: {'mIoU': 0.7836503023463044, 'F1': 0.8774447430669557, 'OA': 0.8717721242171067}
{'ImSurf': 0.7918855070037135, 'Building': 0.8936097831087367, 'LowVeg': 0.7249123745011634, 'Tree': 0.7316647360568483, 'Car': 0.7761791110610599, 'Clutter': 0.5089110350648584}
val: {'mIoU': 0.7506846637805612, 'F1': 0.8567383187146783, 'OA': 0.8479919104976612}
{'ImSurf': 0.7436494707470552, 'Building': 0.8437467025504495, 'LowVeg': 0.7115983717305959, 'Tree': 0.712198258471833, 'Car': 0.7422305154028719, 'Clutter': 0.4344589248690473}
Epoch 30: loss: 15.8997, train accuracy: 0.8718, valid accuracy:0.8480
Start epoch #31, learning rate for this epoch: [2.7993599999999992e-05]


100%|██████████| 312/312 [02:23<00:00,  2.18it/s]


Done epoch #31, time for this epoch: 143.19847512245178s


100%|██████████| 88/88 [00:11<00:00,  7.58it/s]


(array([0.74647274, 0.85400836, 0.71084376, 0.70062525, 0.74200816,
       0.43642218]), 0.7507916554909473, 0.856587757781029, 0.8478032952149137)
train: {'mIoU': 0.7856809204945433, 'F1': 0.878881751709109, 'OA': 0.8743046766672379}
{'ImSurf': 0.794084656117193, 'Building': 0.8894512532531266, 'LowVeg': 0.7311591881362669, 'Tree': 0.7397069099125129, 'Car': 0.7740025950536171, 'Clutter': 0.5378789768554616}
val: {'mIoU': 0.7507916554909473, 'F1': 0.856587757781029, 'OA': 0.8478032952149137}
{'ImSurf': 0.7464727395676155, 'Building': 0.8540083646291202, 'LowVeg': 0.7108437640706153, 'Tree': 0.7006252479145674, 'Car': 0.7420081612728173, 'Clutter': 0.43642217779286796}
Epoch 31: loss: 15.6707, train accuracy: 0.8743, valid accuracy:0.8478
Start epoch #32, learning rate for this epoch: [2.7993599999999992e-05]


100%|██████████| 312/312 [02:21<00:00,  2.20it/s]


Done epoch #32, time for this epoch: 141.98484444618225s


100%|██████████| 88/88 [00:11<00:00,  7.59it/s]


(array([0.74637421, 0.86549913, 0.70790823, 0.70349148, 0.76025271,
       0.44229055]), 0.7567051526683543, 0.8602776109735825, 0.8503237667480817)
train: {'mIoU': 0.7840144799322603, 'F1': 0.8777171926327207, 'OA': 0.8727162740169427}
{'ImSurf': 0.7916973876721354, 'Building': 0.8920396052575257, 'LowVeg': 0.7281718515307167, 'Tree': 0.7306766490149722, 'Car': 0.7774869061859514, 'Clutter': 0.5217304887908069}
val: {'mIoU': 0.7567051526683543, 'F1': 0.8602776109735825, 'OA': 0.8503237667480817}
{'ImSurf': 0.7463742095266238, 'Building': 0.8654991335651284, 'LowVeg': 0.707908228457229, 'Tree': 0.7034914794458432, 'Car': 0.7602527123469468, 'Clutter': 0.44229055475791285}
Epoch 32: loss: 15.8677, train accuracy: 0.8727, valid accuracy:0.8503
Start epoch #33, learning rate for this epoch: [2.7993599999999992e-05]


100%|██████████| 312/312 [02:30<00:00,  2.07it/s]


Done epoch #33, time for this epoch: 150.7429976463318s


100%|██████████| 88/88 [00:11<00:00,  7.79it/s]


(array([0.74448   , 0.85252743, 0.70565832, 0.70403393, 0.7453354 ,
       0.41527129]), 0.7504070158011343, 0.8563511030866906, 0.8465743218919652)
train: {'mIoU': 0.7869364735868942, 'F1': 0.879527732345899, 'OA': 0.8753251632054647}
{'ImSurf': 0.7971524464560604, 'Building': 0.8966690092089917, 'LowVeg': 0.7285057457796039, 'Tree': 0.7371751533271862, 'Car': 0.7751800131626283, 'Clutter': 0.5317838920029156}
val: {'mIoU': 0.7504070158011343, 'F1': 0.8563511030866906, 'OA': 0.8465743218919652}
{'ImSurf': 0.744479995786194, 'Building': 0.8525274322157596, 'LowVeg': 0.7056583215765528, 'Tree': 0.7040339281178615, 'Car': 0.7453354013093038, 'Clutter': 0.4152712874304844}
Epoch 33: loss: 15.6467, train accuracy: 0.8753, valid accuracy:0.8466
Start epoch #34, learning rate for this epoch: [1.6796159999999994e-05]


100%|██████████| 312/312 [02:23<00:00,  2.17it/s]


Done epoch #34, time for this epoch: 143.61338424682617s


100%|██████████| 88/88 [00:12<00:00,  7.22it/s]


(array([0.74626669, 0.8551077 , 0.70110682, 0.70916597, 0.75368278,
       0.46480536]), 0.7530659896107952, 0.8580542853725737, 0.8489642338365936)
train: {'mIoU': 0.7863660773632505, 'F1': 0.8792457145314005, 'OA': 0.8751990886834952}
{'ImSurf': 0.7938808061820856, 'Building': 0.8946986434767797, 'LowVeg': 0.7336118121477342, 'Tree': 0.7385533032683749, 'Car': 0.7710858217412783, 'Clutter': 0.5314491276588422}
val: {'mIoU': 0.7530659896107952, 'F1': 0.8580542853725737, 'OA': 0.8489642338365936}
{'ImSurf': 0.74626668662548, 'Building': 0.8551076993541171, 'LowVeg': 0.7011068178436789, 'Tree': 0.7091659658511226, 'Car': 0.7536827783795775, 'Clutter': 0.46480536449331483}
Epoch 34: loss: 15.7161, train accuracy: 0.8752, valid accuracy:0.8490
Start epoch #35, learning rate for this epoch: [1.6796159999999994e-05]


100%|██████████| 312/312 [02:26<00:00,  2.13it/s]


Done epoch #35, time for this epoch: 146.57439827919006s


100%|██████████| 88/88 [00:11<00:00,  7.33it/s]


(array([0.74339635, 0.85847341, 0.70802594, 0.70571759, 0.73679646,
       0.45481964]), 0.7504819492883275, 0.8563294010072049, 0.8501705873466101)
train: {'mIoU': 0.7884512389144802, 'F1': 0.8805082276443681, 'OA': 0.8761545817057291}
{'ImSurf': 0.7958801320108191, 'Building': 0.8979230546205795, 'LowVeg': 0.7342487290248506, 'Tree': 0.7368434163673038, 'Car': 0.7773608625488483, 'Clutter': 0.5372426944350769}
val: {'mIoU': 0.7504819492883275, 'F1': 0.8563294010072049, 'OA': 0.8501705873466101}
{'ImSurf': 0.7433963481828658, 'Building': 0.8584734116088041, 'LowVeg': 0.7080259363863012, 'Tree': 0.7057175933313862, 'Car': 0.7367964569322807, 'Clutter': 0.4548196438267196}
Epoch 35: loss: 15.5534, train accuracy: 0.8762, valid accuracy:0.8502
Start epoch #36, learning rate for this epoch: [1.6796159999999994e-05]


100%|██████████| 312/312 [02:23<00:00,  2.18it/s]


Done epoch #36, time for this epoch: 143.37231612205505s


100%|██████████| 88/88 [00:11<00:00,  7.56it/s]


(array([0.74229398, 0.8510804 , 0.71311408, 0.7010684 , 0.75728   ,
       0.41513825]), 0.7529673706322171, 0.8580638381178958, 0.8479686553582644)
train: {'mIoU': 0.7915871928174305, 'F1': 0.8824759398648944, 'OA': 0.878197342921526}
{'ImSurf': 0.8002460037760436, 'Building': 0.9011273459956961, 'LowVeg': 0.7387480371919992, 'Tree': 0.7400459021204675, 'Car': 0.777768675002946, 'Clutter': 0.5259822745754886}
val: {'mIoU': 0.7529673706322171, 'F1': 0.8580638381178958, 'OA': 0.8479686553582644}
{'ImSurf': 0.7422939829668318, 'Building': 0.8510803980132127, 'LowVeg': 0.7131140818842117, 'Tree': 0.7010683950811006, 'Car': 0.7572799952157285, 'Clutter': 0.41513825416786765}
Epoch 36: loss: 15.4630, train accuracy: 0.8782, valid accuracy:0.8480
Start epoch #37, learning rate for this epoch: [1.6796159999999994e-05]


100%|██████████| 312/312 [02:25<00:00,  2.14it/s]


Done epoch #37, time for this epoch: 145.92391729354858s


100%|██████████| 88/88 [00:12<00:00,  7.24it/s]


(array([0.75321396, 0.86181305, 0.71056615, 0.70065793, 0.74169564,
       0.45144377]), 0.7535893462014466, 0.8582981929749851, 0.8511383757690516)
train: {'mIoU': 0.7865258740714217, 'F1': 0.8793301592748183, 'OA': 0.8758520254722009}
{'ImSurf': 0.7983245522590066, 'Building': 0.8945238560343527, 'LowVeg': 0.7329549019934924, 'Tree': 0.7384821691530825, 'Car': 0.7683438909171745, 'Clutter': 0.5296998867275141}
val: {'mIoU': 0.7535893462014466, 'F1': 0.8582981929749851, 'OA': 0.8511383757690516}
{'ImSurf': 0.7532139638051565, 'Building': 0.8618130493123456, 'LowVeg': 0.7105661508441432, 'Tree': 0.7006579293623458, 'Car': 0.7416956376832415, 'Clutter': 0.45144377402956265}
Epoch 37: loss: 15.6431, train accuracy: 0.8759, valid accuracy:0.8511
Start epoch #38, learning rate for this epoch: [1.0077695999999996e-05]


100%|██████████| 312/312 [02:24<00:00,  2.16it/s]


Done epoch #38, time for this epoch: 144.70488214492798s


100%|██████████| 88/88 [00:11<00:00,  7.60it/s]


(array([0.75194477, 0.85711836, 0.7083816 , 0.71358001, 0.75154204,
       0.43349818]), 0.7565133570968918, 0.8603554946616795, 0.8500588465661173)
train: {'mIoU': 0.7887184640262205, 'F1': 0.8807140660055042, 'OA': 0.8764003148445716}
{'ImSurf': 0.7996179388990197, 'Building': 0.8960508012440772, 'LowVeg': 0.7365628504708628, 'Tree': 0.7376900486362314, 'Car': 0.7736706808809114, 'Clutter': 0.5310670991255612}
val: {'mIoU': 0.7565133570968918, 'F1': 0.8603554946616795, 'OA': 0.8500588465661173}
{'ImSurf': 0.7519447704394077, 'Building': 0.8571183578608138, 'LowVeg': 0.70838159907136, 'Tree': 0.7135800144972455, 'Car': 0.7515420436156323, 'Clutter': 0.4334981805048482}
Epoch 38: loss: 15.5837, train accuracy: 0.8764, valid accuracy:0.8501
Start epoch #39, learning rate for this epoch: [1.0077695999999996e-05]


100%|██████████| 312/312 [02:23<00:00,  2.18it/s]


Done epoch #39, time for this epoch: 143.08922123908997s


100%|██████████| 88/88 [00:12<00:00,  7.26it/s]


(array([0.74476496, 0.85755754, 0.70726967, 0.70555443, 0.75082271,
       0.45759052]), 0.7531938618161227, 0.8581221422084369, 0.8488146582697246)
train: {'mIoU': 0.7897679358310787, 'F1': 0.8813953835629352, 'OA': 0.8775718059295263}
{'ImSurf': 0.8015007104570863, 'Building': 0.8957850335396774, 'LowVeg': 0.7359805224695358, 'Tree': 0.7417244179187341, 'Car': 0.7738489947703604, 'Clutter': 0.5272988605215414}
val: {'mIoU': 0.7531938618161227, 'F1': 0.8581221422084369, 'OA': 0.8488146582697246}
{'ImSurf': 0.7447649640333002, 'Building': 0.857557540076613, 'LowVeg': 0.7072696697934135, 'Tree': 0.705554429920706, 'Car': 0.7508227052565809, 'Clutter': 0.4575905213037916}
Epoch 39: loss: 15.5396, train accuracy: 0.8776, valid accuracy:0.8488
Start epoch #40, learning rate for this epoch: [1.0077695999999996e-05]


100%|██████████| 312/312 [02:24<00:00,  2.16it/s]


Done epoch #40, time for this epoch: 144.61492228507996s


  5%|▍         | 4/88 [00:00<00:16,  4.98it/s]Exception in thread Thread-48 (_pin_memory_loop):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 51, in _pin_memory_loop
    do_one_step()
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 28, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/opt/conda/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/opt/conda/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 307, in rebuild_storage_fd
    fd = df.detach()
  File "/opt/conda/lib/python3.10/multiprocessing/resource_sharer.py", line 58, in detach
    return red

In [29]:
torch.cuda.empty_cache()

In [30]:
def img_writer(inp):
    (mask,  mask_id, rgb) = inp
    if rgb:
        mask_name_tif = mask_id + '.png'
        mask_tif = label2rgb(mask)
        cv2.imwrite(mask_name_tif, mask_tif)
    else:
        mask_png = mask.astype(np.uint8)
        mask_name_png = mask_id + '.png'
        cv2.imwrite(mask_name_png, mask_png)


def get_args():
    parser = argparse.ArgumentParser()
    arg = parser.add_argument
    arg("-c", "--config_path", type=Path, required=True, help="Path to  config")
    arg("-o", "--output_path", type=Path, help="Path where to save resulting masks.", required=True)
    arg("-t", "--tta", help="Test time augmentation.", default=None, choices=[None, "d4", "lr"])
    arg("--rgb", help="whether output rgb images", action='store_true')
    return parser.parse_args()

In [31]:
test_dataset = PotsdamDataset(data_root='/kaggle/input/deep-data-potsdam-vaihingen/Deep_data_segmentation/Split/Vaihingen/Test',
                              transform=val_aug)

In [32]:
model.cuda()
model.eval()
evaluator = Evaluator(num_class=6)
evaluator.reset()
with torch.no_grad():
    test_loader = DataLoader(
        test_dataset,
        batch_size=2,
        num_workers=4,
        pin_memory=True,
        drop_last=False,
    )
    results = []
    for input in tqdm(test_loader):
        # raw_prediction NxCxHxW
        raw_predictions = model(input['img'].cuda())

        image_ids = input["img_id"]
        masks_true = input['gt_semantic_seg']

        raw_predictions = nn.Softmax(dim=1)(raw_predictions)
        predictions = raw_predictions.argmax(dim=1)

        for i in range(raw_predictions.shape[0]):
            mask = predictions[i].cpu().numpy()
            evaluator.add_batch(pre_image=mask, gt_image=masks_true[i].cpu().numpy())
            mask_name = image_ids[i]
iou_per_class = evaluator.Intersection_over_Union()
f1_per_class = evaluator.F1()
OA = evaluator.OA()
for class_name, class_iou, class_f1 in zip(CLASSES, iou_per_class, f1_per_class):
    print('F1_{}:{}, IOU_{}:{}'.format(class_name, class_f1, class_name, class_iou))
print('F1:{}, mIOU:{}, OA:{}'.format(np.nanmean(f1_per_class[:-1]), np.nanmean(iou_per_class[:-1]), OA))
t0 = time.time()
mpp.Pool(processes=2).map(img_writer, results)
t1 = time.time()
img_write_time = t1 - t0
print('images writing spends: {} s'.format(img_write_time))

100%|██████████| 235/235 [00:05<00:00, 40.25it/s]

F1_ImSurf:0.5618505399074194, IOU_ImSurf:0.39067604271898865
F1_Building:0.7103269497812126, IOU_Building:0.5507806413886907
F1_LowVeg:0.06093045547741564, IOU_LowVeg:0.031422522028428455
F1_Tree:0.04499079610776339, IOU_Tree:0.023013086597337244
F1_Car:0.2496819635751765, IOU_Car:0.14264948333913852
F1_Clutter:0.08056004587906423, IOU_Clutter:0.0419705996564811
F1:0.3255561409697975, mIOU:0.2277083552145167, OA:0.4430487450132977


images writing spends: 0.05967283248901367 s
